/*
 * Automatically generated C config: don't edit
 */
#define AUTOCONF_INCLUDED
#define CONFIG_X86 1
#define CONFIG_MMU 1
#define CONFIG_UID16 1
#define CONFIG_GENERIC_ISA_DMA 1

/*
 * Code maturity level options
 */
#define CONFIG_EXPERIMENTAL 1
#define CONFIG_CLEAN_COMPILE 1
#define CONFIG_STANDALONE 1

/*
 * General setup
 */
#define CONFIG_SWAP 1
#define CONFIG_SYSVIPC 1
#define CONFIG_POSIX_MQUEUE 1
#define CONFIG_BSD_PROCESS_ACCT 1
#define CONFIG_SYSCTL 1
#undef CONFIG_AUDIT
#define CONFIG_LOG_BUF_SHIFT 17
#define CONFIG_HOTPLUG 1
#undef CONFIG_IKCONFIG
#undef CONFIG_EMBEDDED
#define CONFIG_KALLSYMS 1
#undef CONFIG_KALLSYMS_ALL
#define CONFIG_FUTEX 1
#define CONFIG_EPOLL 1
#define CONFIG_IOSCHED_NOOP 1
#define CONFIG_IOSCHED_AS 1
#define CONFIG_IOSCHED_DEADLINE 1
#define CONFIG_IOSCHED_CFQ 1
#define CONFIG_CC_OPTIMIZE_FOR_SIZE 1

/*
 * Loadable module support
 */
#define CONFIG_MODULES 1
#define CONFIG_MODULE_UNLOAD 1
#undef CONFIG_MODULE_FORCE_UNLOAD
#define CONFIG_OBSOLETE_MODPARM 1
#undef CONFIG_MODVERSIONS
#define CONFIG_KMOD 1
#define CONFIG_STOP_MACHINE 1

/*
 * Processor type and features
 */
#undef CONFIG_X86_PC
#undef CONFIG_X86_ELAN
#undef CONFIG_X86_VOYAGER
#undef CONFIG_X86_NUMAQ
#undef CONFIG_X86_SUMMIT
#undef CONFIG_X86_BIGSMP
#undef CONFIG_X86_VISWS
#define CONFIG_X86_GENERICARCH 1
#undef CONFIG_X86_ES7000
#define CONFIG_X86_CYCLONE_TIMER 1
#undef CONFIG_M386
#undef CONFIG_M486
#undef CONFIG_M586
#undef CONFIG_M586TSC
#undef CONFIG_M586MMX
#define CONFIG_M686 1
#undef CONFIG_MPENTIUMII
#undef CONFIG_MPENTIUMIII
#undef CONFIG_MPENTIUMM
#undef CONFIG_MPENTIUM4
#undef CONFIG_MK6
#undef CONFIG_MK7
#undef CONFIG_MK8
#undef CONFIG_MCRUSOE
#undef CONFIG_MWINCHIPC6
#undef CONFIG_MWINCHIP2
#undef CONFIG_MWINCHIP3D
#undef CONFIG_MCYRIXIII
#undef CONFIG_MVIAC3_2
#define CONFIG_X86_GENERIC 1
#define CONFIG_X86_CMPXCHG 1
#define CONFIG_X86_XADD 1
#define CONFIG_X86_L1_CACHE_SHIFT 7
#define CONFIG_RWSEM_XCHGADD_ALGORITHM 1
#define CONFIG_X86_PPRO_FENCE 1
#define CONFIG_X86_WP_WORKS_OK 1
#define CONFIG_X86_INVLPG 1
#define CONFIG_X86_BSWAP 1
#define CONFIG_X86_POPAD_OK 1
#define CONFIG_X86_GOOD_APIC 1
#define CONFIG_X86_INTEL_USERCOPY 1
#define CONFIG_X86_USE_PPRO_CHECKSUM 1
#define CONFIG_X86_4G 1
#define CONFIG_X86_SWITCH_PAGETABLES 1
#define CONFIG_X86_4G_VM_LAYOUT 1
#define CONFIG_X86_UACCESS_INDIRECT 1
#define CONFIG_X86_HIGH_ENTRY 1
#define CONFIG_HPET_TIMER 1
#define CONFIG_HPET_EMULATE_RTC 1
#define CONFIG_SMP 1
#define CONFIG_NR_CPUS 32
#define CONFIG_SCHED_SMT 1
#undef CONFIG_PREEMPT
#define CONFIG_X86_LOCAL_APIC 1
#define CONFIG_X86_IO_APIC 1
#define CONFIG_X86_TSC 1
#define CONFIG_X86_MCE 1
#undef CONFIG_X86_MCE_NONFATAL
#define CONFIG_X86_MCE_P4THERMAL 1
#define CONFIG_TOSHIBA_MODULE 1
#define CONFIG_I8K_MODULE 1
#define CONFIG_MICROCODE_MODULE 1
#define CONFIG_X86_MSR_MODULE 1
#define CONFIG_X86_CPUID_MODULE 1

/*
 * Firmware Drivers
 */
#define CONFIG_EDD_MODULE 1
#undef CONFIG_NOHIGHMEM
#undef CONFIG_HIGHMEM4G
#define CONFIG_HIGHMEM64G 1
#define CONFIG_HIGHMEM 1
#define CONFIG_X86_PAE 1
#undef CONFIG_NUMA
#define CONFIG_HIGHPTE 1
#undef CONFIG_MATH_EMULATION
#define CONFIG_MTRR 1
#undef CONFIG_EFI
#undef CONFIG_IRQBALANCE
#define CONFIG_HAVE_DEC_LOCK 1
#define CONFIG_REGPARM 1

/*
 * Power management options (ACPI, APM)
 */
#define CONFIG_PM 1
#undef CONFIG_SOFTWARE_SUSPEND
#undef CONFIG_PM_DISK

/*
 * ACPI (Advanced Configuration and Power Interface) Support
 */
#define CONFIG_ACPI 1
#define CONFIG_ACPI_BOOT 1
#define CONFIG_ACPI_INTERPRETER 1
#define CONFIG_ACPI_SLEEP 1
#define CONFIG_ACPI_SLEEP_PROC_FS 1
#define CONFIG_ACPI_AC_MODULE 1
#define CONFIG_ACPI_BATTERY_MODULE 1
#define CONFIG_ACPI_BUTTON_MODULE 1
#define CONFIG_ACPI_FAN 1
#define CONFIG_ACPI_PROCESSOR 1
#define CONFIG_ACPI_THERMAL 1
#define CONFIG_ACPI_ASUS_MODULE 1
#define CONFIG_ACPI_TOSHIBA_MODULE 1
#undef CONFIG_ACPI_DEBUG
#define CONFIG_ACPI_BUS 1
#define CONFIG_ACPI_EC 1
#define CONFIG_ACPI_POWER 1
#define CONFIG_ACPI_PCI 1
#define CONFIG_ACPI_SYSTEM 1
#define CONFIG_X86_PM_TIMER 1

/*
 * APM (Advanced Power Management) BIOS Support
 */
#define CONFIG_APM 1
#undef CONFIG_APM_IGNORE_USER_SUSPEND
#undef CONFIG_APM_DO_ENABLE
#define CONFIG_APM_CPU_IDLE 1
#undef CONFIG_APM_DISPLAY_BLANK
#define CONFIG_APM_RTC_IS_GMT 1
#undef CONFIG_APM_ALLOW_INTS
#undef CONFIG_APM_REAL_MODE_POWER_OFF

/*
 * CPU Frequency scaling
 */
#define CONFIG_CPU_FREQ 1
#undef CONFIG_CPU_FREQ_PROC_INTF
#undef CONFIG_CPU_FREQ_DEFAULT_GOV_PERFORMANCE
#define CONFIG_CPU_FREQ_DEFAULT_GOV_USERSPACE 1
#define CONFIG_CPU_FREQ_GOV_PERFORMANCE 1
#define CONFIG_CPU_FREQ_GOV_POWERSAVE_MODULE 1
#define CONFIG_CPU_FREQ_GOV_USERSPACE 1
#undef CONFIG_CPU_FREQ_24_API
#define CONFIG_CPU_FREQ_TABLE 1

/*
 * CPUFreq processor drivers
 */
#define CONFIG_X86_ACPI_CPUFREQ_MODULE 1
#undef CONFIG_X86_ACPI_CPUFREQ_PROC_INTF
#define CONFIG_X86_POWERNOW_K6_MODULE 1
#define CONFIG_X86_POWERNOW_K7 1
#define CONFIG_X86_POWERNOW_K8_MODULE 1
#undef CONFIG_X86_GX_SUSPMOD
#define CONFIG_X86_SPEEDSTEP_CENTRINO 1
#define CONFIG_X86_SPEEDSTEP_CENTRINO_TABLE 1
#define CONFIG_X86_SPEEDSTEP_CENTRINO_ACPI 1
#define CONFIG_X86_SPEEDSTEP_ICH 1
#define CONFIG_X86_SPEEDSTEP_SMI_MODULE 1
#define CONFIG_X86_P4_CLOCKMOD_MODULE 1
#define CONFIG_X86_SPEEDSTEP_LIB 1
#undef CONFIG_X86_SPEEDSTEP_RELAXED_CAP_CHECK
#define CONFIG_X86_LONGRUN 1
#undef CONFIG_X86_LONGHAUL

/*
 * Bus options (PCI, PCMCIA, EISA, MCA, ISA)
 */
#define CONFIG_PCI 1
#undef CONFIG_PCI_GOBIOS
#undef CONFIG_PCI_GOMMCONFIG
#undef CONFIG_PCI_GODIRECT
#define CONFIG_PCI_GOANY 1
#define CONFIG_PCI_BIOS 1
#define CONFIG_PCI_DIRECT 1
#define CONFIG_PCI_MMCONFIG 1
#define CONFIG_PCI_USE_VECTOR 1
#define CONFIG_PCI_LEGACY_PROC 1
#undef CONFIG_PCI_NAMES
#define CONFIG_ISA 1
#undef CONFIG_EISA
#undef CONFIG_MCA
#undef CONFIG_SCx200

/*
 * PCMCIA/CardBus support
 */
#define CONFIG_PCMCIA_MODULE 1
#undef CONFIG_PCMCIA_DEBUG
#define CONFIG_YENTA_MODULE 1
#define CONFIG_CARDBUS 1
#define CONFIG_I82092_MODULE 1
#define CONFIG_I82365_MODULE 1
#define CONFIG_TCIC_MODULE 1
#define CONFIG_PCMCIA_PROBE 1

/*
 * PCI Hotplug Support
 */
#define CONFIG_HOTPLUG_PCI 1
#undef CONFIG_HOTPLUG_PCI_FAKE
#define CONFIG_HOTPLUG_PCI_COMPAQ_MODULE 1
#undef CONFIG_HOTPLUG_PCI_COMPAQ_NVRAM
#define CONFIG_HOTPLUG_PCI_IBM_MODULE 1
#undef CONFIG_HOTPLUG_PCI_ACPI
#undef CONFIG_HOTPLUG_PCI_CPCI
#define CONFIG_HOTPLUG_PCI_PCIE_MODULE 1
#define CONFIG_HOTPLUG_PCI_PCIE_POLL_EVENT_MODE 1
#define CONFIG_HOTPLUG_PCI_SHPC_MODULE 1
#define CONFIG_HOTPLUG_PCI_SHPC_POLL_EVENT_MODE 1

/*
 * Executable file formats
 */
#define CONFIG_BINFMT_ELF 1
#undef CONFIG_BINFMT_AOUT
#define CONFIG_BINFMT_MISC_MODULE 1

/*
 * Device Drivers
 */

/*
 * Generic Driver Options
 */
#define CONFIG_FW_LOADER 1
#undef CONFIG_DEBUG_DRIVER

/*
 * Memory Technology Devices (MTD)
 */
#define CONFIG_MTD_MODULE 1
#undef CONFIG_MTD_DEBUG
#define CONFIG_MTD_PARTITIONS_MODULE 1
#define CONFIG_MTD_CONCAT_MODULE 1
#define CONFIG_MTD_REDBOOT_PARTS_MODULE 1
#define CONFIG_MTD_CMDLINE_PARTS_MODULE 1

/*
 * User Modules And Translation Layers
 */
#define CONFIG_MTD_CHAR_MODULE 1
#define CONFIG_MTD_BLOCK_MODULE 1
#define CONFIG_MTD_BLOCK_RO_MODULE 1
#define CONFIG_FTL_MODULE 1
#define CONFIG_NFTL_MODULE 1
#define CONFIG_NFTL_RW 1
#define CONFIG_INFTL_MODULE 1

/*
 * RAM/ROM/Flash chip drivers
 */
#define CONFIG_MTD_CFI_MODULE 1
#define CONFIG_MTD_JEDECPROBE_MODULE 1
#define CONFIG_MTD_GEN_PROBE_MODULE 1
#undef CONFIG_MTD_CFI_ADV_OPTIONS
#define CONFIG_MTD_CFI_INTELEXT_MODULE 1
#define CONFIG_MTD_CFI_AMDSTD_MODULE 1
#define CONFIG_MTD_CFI_STAA_MODULE 1
#define CONFIG_MTD_RAM_MODULE 1
#define CONFIG_MTD_ROM_MODULE 1
#define CONFIG_MTD_ABSENT_MODULE 1
#undef CONFIG_MTD_OBSOLETE_CHIPS

/*
 * Mapping drivers for chip access
 */
#define CONFIG_MTD_COMPLEX_MAPPINGS 1
#undef CONFIG_MTD_PHYSMAP
#undef CONFIG_MTD_PNC2000
#define CONFIG_MTD_SC520CDP_MODULE 1
#define CONFIG_MTD_NETSC520_MODULE 1
#define CONFIG_MTD_SBC_GXX_MODULE 1
#define CONFIG_MTD_ELAN_104NC_MODULE 1
#define CONFIG_MTD_SCx200_DOCFLASH_MODULE 1
#define CONFIG_MTD_AMD76XROM_MODULE 1
#define CONFIG_MTD_ICH2ROM_MODULE 1
#define CONFIG_MTD_SCB2_FLASH_MODULE 1
#undef CONFIG_MTD_NETtel
#undef CONFIG_MTD_DILNETPC
#define CONFIG_MTD_L440GX_MODULE 1
#define CONFIG_MTD_PCI_MODULE 1

/*
 * Self-contained MTD device drivers
 */
#define CONFIG_MTD_PMC551_MODULE 1
#undef CONFIG_MTD_PMC551_BUGFIX
#undef CONFIG_MTD_PMC551_DEBUG
#undef CONFIG_MTD_SLRAM
#define CONFIG_MTD_MTDRAM_MODULE 1
#define CONFIG_MTDRAM_TOTAL_SIZE 4096
#define CONFIG_MTDRAM_ERASE_SIZE 128
#undef CONFIG_MTD_BLKMTD

/*
 * Disk-On-Chip Device Drivers
 */
#define CONFIG_MTD_DOC2000_MODULE 1
#undef CONFIG_MTD_DOC2001
#define CONFIG_MTD_DOC2001PLUS_MODULE 1
#define CONFIG_MTD_DOCPROBE_MODULE 1
#undef CONFIG_MTD_DOCPROBE_ADVANCED
#define CONFIG_MTD_DOCPROBE_ADDRESS 0x0

/*
 * NAND Flash Device Drivers
 */
#define CONFIG_MTD_NAND_MODULE 1
#undef CONFIG_MTD_NAND_VERIFY_WRITE
#define CONFIG_MTD_NAND_IDS_MODULE 1

/*
 * Parallel port support
 */
#define CONFIG_PARPORT_MODULE 1
#define CONFIG_PARPORT_PC_MODULE 1
#define CONFIG_PARPORT_PC_CML1_MODULE 1
#define CONFIG_PARPORT_SERIAL_MODULE 1
#undef CONFIG_PARPORT_PC_FIFO
#undef CONFIG_PARPORT_PC_SUPERIO
#define CONFIG_PARPORT_PC_PCMCIA_MODULE 1
#undef CONFIG_PARPORT_OTHER
#define CONFIG_PARPORT_1284 1

/*
 * Plug and Play support
 */
#define CONFIG_PNP 1
#undef CONFIG_PNP_DEBUG

/*
 * Protocols
 */
#define CONFIG_ISAPNP 1
#undef CONFIG_PNPBIOS

/*
 * Block devices
 */
#define CONFIG_BLK_DEV_FD_MODULE 1
#undef CONFIG_BLK_DEV_XD
#undef CONFIG_PARIDE
#define CONFIG_BLK_CPQ_DA_MODULE 1
#define CONFIG_BLK_CPQ_CISS_DA_MODULE 1
#define CONFIG_CISS_SCSI_TAPE 1
#define CONFIG_BLK_DEV_DAC960_MODULE 1
#define CONFIG_BLK_DEV_UMEM_MODULE 1
#define CONFIG_BLK_DEV_LOOP_MODULE 1
#define CONFIG_BLK_DEV_CRYPTOLOOP_MODULE 1
#define CONFIG_BLK_DEV_NBD_MODULE 1
#define CONFIG_BLK_DEV_CARMEL_MODULE 1
#define CONFIG_BLK_DEV_RAM 1
#define CONFIG_BLK_DEV_RAM_SIZE 16384
#define CONFIG_BLK_DEV_INITRD 1
#define CONFIG_LBD 1

/*
 * ATA/ATAPI/MFM/RLL support
 */
#define CONFIG_IDE 1
#define CONFIG_BLK_DEV_IDE 1

/*
 * Please see Documentation/ide.txt for help/info on IDE drives
 */
#undef CONFIG_BLK_DEV_HD_IDE
#define CONFIG_BLK_DEV_IDEDISK 1
#define CONFIG_IDEDISK_MULTI_MODE 1
#undef CONFIG_IDEDISK_STROKE
#define CONFIG_BLK_DEV_IDECS_MODULE 1
#define CONFIG_BLK_DEV_IDECD 1
#define CONFIG_BLK_DEV_IDETAPE_MODULE 1
#define CONFIG_BLK_DEV_IDEFLOPPY 1
#undef CONFIG_BLK_DEV_IDESCSI
#undef CONFIG_IDE_TASK_IOCTL
#undef CONFIG_IDE_TASKFILE_IO

/*
 * IDE chipset support/bugfixes
 */
#define CONFIG_IDE_GENERIC 1
#undef CONFIG_BLK_DEV_CMD640
#define CONFIG_BLK_DEV_IDEPNP 1
#define CONFIG_BLK_DEV_IDEPCI 1
#define CONFIG_IDEPCI_SHARE_IRQ 1
#undef CONFIG_BLK_DEV_OFFBOARD
#define CONFIG_BLK_DEV_GENERIC 1
#undef CONFIG_BLK_DEV_OPTI621
#define CONFIG_BLK_DEV_RZ1000 1
#define CONFIG_BLK_DEV_IDEDMA_PCI 1
#undef CONFIG_BLK_DEV_IDEDMA_FORCED
#define CONFIG_IDEDMA_PCI_AUTO 1
#undef CONFIG_IDEDMA_ONLYDISK
#define CONFIG_BLK_DEV_ADMA 1
#define CONFIG_BLK_DEV_AEC62XX 1
#define CONFIG_BLK_DEV_ALI15X3 1
#undef CONFIG_WDC_ALI15X3
#define CONFIG_BLK_DEV_AMD74XX 1
#define CONFIG_BLK_DEV_ATIIXP 1
#define CONFIG_BLK_DEV_CMD64X 1
#define CONFIG_BLK_DEV_TRIFLEX 1
#define CONFIG_BLK_DEV_CY82C693 1
#define CONFIG_BLK_DEV_CS5520 1
#define CONFIG_BLK_DEV_CS5530 1
#define CONFIG_BLK_DEV_HPT34X 1
#undef CONFIG_HPT34X_AUTODMA
#define CONFIG_BLK_DEV_HPT366 1
#undef CONFIG_BLK_DEV_SC1200
#define CONFIG_BLK_DEV_PIIX 1
#undef CONFIG_BLK_DEV_NS87415
#define CONFIG_BLK_DEV_PDC202XX_OLD 1
#undef CONFIG_PDC202XX_BURST
#define CONFIG_BLK_DEV_PDC202XX_NEW 1
#define CONFIG_PDC202XX_FORCE 1
#define CONFIG_BLK_DEV_SVWKS 1
#define CONFIG_BLK_DEV_SIIMAGE 1
#define CONFIG_BLK_DEV_SIS5513 1
#define CONFIG_BLK_DEV_SLC90E66 1
#undef CONFIG_BLK_DEV_TRM290
#define CONFIG_BLK_DEV_VIA82CXXX 1
#undef CONFIG_IDE_ARM
#undef CONFIG_IDE_CHIPSETS
#define CONFIG_BLK_DEV_IDEDMA 1
#undef CONFIG_IDEDMA_IVB
#define CONFIG_IDEDMA_AUTO 1
#undef CONFIG_BLK_DEV_HD

/*
 * SCSI device support
 */
#define CONFIG_SCSI_MODULE 1
#define CONFIG_SCSI_PROC_FS 1

/*
 * SCSI support type (disk, tape, CD-ROM)
 */
#define CONFIG_BLK_DEV_SD_MODULE 1
#define CONFIG_CHR_DEV_ST_MODULE 1
#define CONFIG_CHR_DEV_OSST_MODULE 1
#define CONFIG_BLK_DEV_SR_MODULE 1
#define CONFIG_BLK_DEV_SR_VENDOR 1
#define CONFIG_CHR_DEV_SG_MODULE 1

/*
 * Some SCSI devices (e.g. CD jukebox) support multiple LUNs
 */
#undef CONFIG_SCSI_MULTI_LUN
#define CONFIG_SCSI_CONSTANTS 1
#define CONFIG_SCSI_LOGGING 1

/*
 * SCSI Transport Attributes
 */
#define CONFIG_SCSI_SPI_ATTRS_MODULE 1
#define CONFIG_SCSI_FC_ATTRS_MODULE 1

/*
 * SCSI low-level drivers
 */
#define CONFIG_BLK_DEV_3W_XXXX_RAID_MODULE 1
#undef CONFIG_SCSI_7000FASST
#define CONFIG_SCSI_ACARD_MODULE 1
#define CONFIG_SCSI_AHA152X_MODULE 1
#define CONFIG_SCSI_AHA1542_MODULE 1
#define CONFIG_SCSI_AACRAID_MODULE 1
#define CONFIG_SCSI_AIC7XXX_MODULE 1
#define CONFIG_AIC7XXX_CMDS_PER_DEVICE 4
#define CONFIG_AIC7XXX_RESET_DELAY_MS 15000
#undef CONFIG_AIC7XXX_BUILD_FIRMWARE
#undef CONFIG_AIC7XXX_DEBUG_ENABLE
#define CONFIG_AIC7XXX_DEBUG_MASK 0
#undef CONFIG_AIC7XXX_REG_PRETTY_PRINT
#define CONFIG_SCSI_AIC7XXX_OLD_MODULE 1
#define CONFIG_SCSI_AIC79XX_MODULE 1
#define CONFIG_AIC79XX_CMDS_PER_DEVICE 4
#define CONFIG_AIC79XX_RESET_DELAY_MS 15000
#undef CONFIG_AIC79XX_BUILD_FIRMWARE
#undef CONFIG_AIC79XX_ENABLE_RD_STRM
#undef CONFIG_AIC79XX_DEBUG_ENABLE
#define CONFIG_AIC79XX_DEBUG_MASK 0
#undef CONFIG_AIC79XX_REG_PRETTY_PRINT
#undef CONFIG_SCSI_DPT_I2O
#define CONFIG_SCSI_ADVANSYS_MODULE 1
#define CONFIG_SCSI_IN2000_MODULE 1
#define CONFIG_SCSI_MEGARAID_MODULE 1
#define CONFIG_SCSI_SATA 1
#define CONFIG_SCSI_SATA_SVW_MODULE 1
#define CONFIG_SCSI_ATA_PIIX_MODULE 1
#define CONFIG_SCSI_SATA_PROMISE_MODULE 1
#define CONFIG_SCSI_SATA_SX4_MODULE 1
#define CONFIG_SCSI_SATA_SIL_MODULE 1
#define CONFIG_SCSI_SATA_SIS_MODULE 1
#define CONFIG_SCSI_SATA_VIA_MODULE 1
#define CONFIG_SCSI_SATA_VITESSE_MODULE 1
#define CONFIG_SCSI_BUSLOGIC_MODULE 1
#undef CONFIG_SCSI_OMIT_FLASHPOINT
#undef CONFIG_SCSI_CPQFCTS
#undef CONFIG_SCSI_DMX3191D
#undef CONFIG_SCSI_DTC3280
#undef CONFIG_SCSI_EATA
#undef CONFIG_SCSI_EATA_PIO
#define CONFIG_SCSI_FUTURE_DOMAIN_MODULE 1
#define CONFIG_SCSI_GDTH_MODULE 1
#undef CONFIG_SCSI_GENERIC_NCR5380
#undef CONFIG_SCSI_GENERIC_NCR5380_MMIO
#define CONFIG_SCSI_IPS_MODULE 1
#define CONFIG_SCSI_INIA100_MODULE 1
#define CONFIG_SCSI_PPA_MODULE 1
#define CONFIG_SCSI_IMM_MODULE 1
#undef CONFIG_SCSI_IZIP_EPP16
#undef CONFIG_SCSI_IZIP_SLOW_CTR
#undef CONFIG_SCSI_NCR53C406A
#define CONFIG_SCSI_SYM53C8XX_2_MODULE 1
#define CONFIG_SCSI_SYM53C8XX_DMA_ADDRESSING_MODE 1
#define CONFIG_SCSI_SYM53C8XX_DEFAULT_TAGS 16
#define CONFIG_SCSI_SYM53C8XX_MAX_TAGS 64
#undef CONFIG_SCSI_SYM53C8XX_IOMAPPED
#undef CONFIG_SCSI_IPR
#undef CONFIG_SCSI_PAS16
#undef CONFIG_SCSI_PSI240I
#define CONFIG_SCSI_QLOGIC_FAS_MODULE 1
#define CONFIG_SCSI_QLOGIC_ISP_MODULE 1
#undef CONFIG_SCSI_QLOGIC_FC
#define CONFIG_SCSI_QLOGIC_1280_MODULE 1
#define CONFIG_SCSI_QLA2XXX_MODULE 1
#define CONFIG_SCSI_QLA21XX_MODULE 1
#define CONFIG_SCSI_QLA22XX_MODULE 1
#define CONFIG_SCSI_QLA2300_MODULE 1
#define CONFIG_SCSI_QLA2322_MODULE 1
#define CONFIG_SCSI_QLA6312_MODULE 1
#define CONFIG_SCSI_QLA6322_MODULE 1
#undef CONFIG_SCSI_SYM53C416
#undef CONFIG_SCSI_DC395x
#define CONFIG_SCSI_DC390T_MODULE 1
#undef CONFIG_SCSI_T128
#undef CONFIG_SCSI_U14_34F
#undef CONFIG_SCSI_ULTRASTOR
#undef CONFIG_SCSI_NSP32
#undef CONFIG_SCSI_DEBUG

/*
 * PCMCIA SCSI adapter support
 */
#define CONFIG_PCMCIA_AHA152X_MODULE 1
#define CONFIG_PCMCIA_FDOMAIN_MODULE 1
#define CONFIG_PCMCIA_NINJA_SCSI_MODULE 1
#define CONFIG_PCMCIA_QLOGIC_MODULE 1
#define CONFIG_PCMCIA_SYM53C500_MODULE 1

/*
 * Old CD-ROM drivers (not SCSI, not IDE)
 */
#undef CONFIG_CD_NO_IDESCSI

/*
 * Multi-device support (RAID and LVM)
 */
#define CONFIG_MD 1
#define CONFIG_BLK_DEV_MD 1
#define CONFIG_MD_LINEAR_MODULE 1
#define CONFIG_MD_RAID0_MODULE 1
#define CONFIG_MD_RAID1_MODULE 1
#define CONFIG_MD_RAID5_MODULE 1
#define CONFIG_MD_RAID6_MODULE 1
#define CONFIG_MD_MULTIPATH_MODULE 1
#define CONFIG_BLK_DEV_DM_MODULE 1
#define CONFIG_DM_CRYPT_MODULE 1

/*
 * Fusion MPT device support
 */
#define CONFIG_FUSION_MODULE 1
#define CONFIG_FUSION_MAX_SGE 40
#undef CONFIG_FUSION_ISENSE
#define CONFIG_FUSION_CTL_MODULE 1
#define CONFIG_FUSION_LAN_MODULE 1

/*
 * IEEE 1394 (FireWire) support
 */
#define CONFIG_IEEE1394_MODULE 1

/*
 * Subsystem Options
 */
#undef CONFIG_IEEE1394_VERBOSEDEBUG
#define CONFIG_IEEE1394_OUI_DB 1
#undef CONFIG_IEEE1394_EXTRA_CONFIG_ROMS

/*
 * Device Drivers
 */
#undef CONFIG_IEEE1394_PCILYNX
#define CONFIG_IEEE1394_OHCI1394_MODULE 1

/*
 * Protocol Drivers
 */
#define CONFIG_IEEE1394_VIDEO1394_MODULE 1
#define CONFIG_IEEE1394_SBP2_MODULE 1
#undef CONFIG_IEEE1394_SBP2_PHYS_DMA
#undef CONFIG_IEEE1394_ETH1394
#define CONFIG_IEEE1394_DV1394_MODULE 1
#define CONFIG_IEEE1394_RAWIO_MODULE 1
#define CONFIG_IEEE1394_CMP_MODULE 1
#define CONFIG_IEEE1394_AMDTP_MODULE 1

/*
 * I2O device support
 */
#define CONFIG_I2O_MODULE 1
#define CONFIG_I2O_CONFIG_MODULE 1
#define CONFIG_I2O_BLOCK_MODULE 1
#define CONFIG_I2O_SCSI_MODULE 1
#define CONFIG_I2O_PROC_MODULE 1

/*
 * Networking support
 */
#define CONFIG_NET 1

/*
 * Networking options
 */
#define CONFIG_PACKET 1
#define CONFIG_PACKET_MMAP 1
#define CONFIG_NETLINK_DEV 1
#define CONFIG_UNIX 1
#define CONFIG_NET_KEY_MODULE 1
#define CONFIG_INET 1
#define CONFIG_IP_MULTICAST 1
#define CONFIG_IP_ADVANCED_ROUTER 1
#define CONFIG_IP_MULTIPLE_TABLES 1
#define CONFIG_IP_ROUTE_FWMARK 1
#define CONFIG_IP_ROUTE_NAT 1
#define CONFIG_IP_ROUTE_MULTIPATH 1
#define CONFIG_IP_ROUTE_TOS 1
#define CONFIG_IP_ROUTE_VERBOSE 1
#undef CONFIG_IP_PNP
#define CONFIG_NET_IPIP_MODULE 1
#define CONFIG_NET_IPGRE_MODULE 1
#define CONFIG_NET_IPGRE_BROADCAST 1
#define CONFIG_IP_MROUTE 1
#define CONFIG_IP_PIMSM_V1 1
#define CONFIG_IP_PIMSM_V2 1
#undef CONFIG_ARPD
#define CONFIG_SYN_COOKIES 1
#define CONFIG_INET_AH_MODULE 1
#define CONFIG_INET_ESP_MODULE 1
#define CONFIG_INET_IPCOMP_MODULE 1

/*
 * IP: Virtual Server Configuration
 */
#define CONFIG_IP_VS_MODULE 1
#undef CONFIG_IP_VS_DEBUG
#define CONFIG_IP_VS_TAB_BITS 12

/*
 * IPVS transport protocol load balancing support
 */
#define CONFIG_IP_VS_PROTO_TCP 1
#define CONFIG_IP_VS_PROTO_UDP 1
#define CONFIG_IP_VS_PROTO_ESP 1
#define CONFIG_IP_VS_PROTO_AH 1

/*
 * IPVS scheduler
 */
#define CONFIG_IP_VS_RR_MODULE 1
#define CONFIG_IP_VS_WRR_MODULE 1
#define CONFIG_IP_VS_LC_MODULE 1
#define CONFIG_IP_VS_WLC_MODULE 1
#define CONFIG_IP_VS_LBLC_MODULE 1
#define CONFIG_IP_VS_LBLCR_MODULE 1
#define CONFIG_IP_VS_DH_MODULE 1
#define CONFIG_IP_VS_SH_MODULE 1
#define CONFIG_IP_VS_SED_MODULE 1
#define CONFIG_IP_VS_NQ_MODULE 1

/*
 * IPVS application helper
 */
#define CONFIG_IP_VS_FTP_MODULE 1
#define CONFIG_IPV6_MODULE 1
#define CONFIG_IPV6_PRIVACY 1
#define CONFIG_INET6_AH_MODULE 1
#define CONFIG_INET6_ESP_MODULE 1
#define CONFIG_INET6_IPCOMP_MODULE 1
#define CONFIG_IPV6_TUNNEL_MODULE 1
#define CONFIG_NETFILTER 1
#undef CONFIG_NETFILTER_DEBUG
#define CONFIG_BRIDGE_NETFILTER 1

/*
 * IP: Netfilter Configuration
 */
#define CONFIG_IP_NF_CONNTRACK_MODULE 1
#define CONFIG_IP_NF_FTP_MODULE 1
#define CONFIG_IP_NF_IRC_MODULE 1
#define CONFIG_IP_NF_TFTP_MODULE 1
#define CONFIG_IP_NF_AMANDA_MODULE 1
#define CONFIG_IP_NF_QUEUE_MODULE 1
#define CONFIG_IP_NF_IPTABLES_MODULE 1
#define CONFIG_IP_NF_MATCH_LIMIT_MODULE 1
#define CONFIG_IP_NF_MATCH_IPRANGE_MODULE 1
#define CONFIG_IP_NF_MATCH_MAC_MODULE 1
#define CONFIG_IP_NF_MATCH_PKTTYPE_MODULE 1
#define CONFIG_IP_NF_MATCH_MARK_MODULE 1
#define CONFIG_IP_NF_MATCH_MULTIPORT_MODULE 1
#define CONFIG_IP_NF_MATCH_TOS_MODULE 1
#define CONFIG_IP_NF_MATCH_RECENT_MODULE 1
#define CONFIG_IP_NF_MATCH_ECN_MODULE 1
#define CONFIG_IP_NF_MATCH_DSCP_MODULE 1
#define CONFIG_IP_NF_MATCH_AH_ESP_MODULE 1
#define CONFIG_IP_NF_MATCH_LENGTH_MODULE 1
#define CONFIG_IP_NF_MATCH_TTL_MODULE 1
#define CONFIG_IP_NF_MATCH_TCPMSS_MODULE 1
#define CONFIG_IP_NF_MATCH_HELPER_MODULE 1
#define CONFIG_IP_NF_MATCH_STATE_MODULE 1
#define CONFIG_IP_NF_MATCH_CONNTRACK_MODULE 1
#define CONFIG_IP_NF_MATCH_OWNER_MODULE 1
#define CONFIG_IP_NF_MATCH_PHYSDEV_MODULE 1
#define CONFIG_IP_NF_FILTER_MODULE 1
#define CONFIG_IP_NF_TARGET_REJECT_MODULE 1
#define CONFIG_IP_NF_NAT_MODULE 1
#define CONFIG_IP_NF_NAT_NEEDED 1
#define CONFIG_IP_NF_TARGET_MASQUERADE_MODULE 1
#define CONFIG_IP_NF_TARGET_REDIRECT_MODULE 1
#define CONFIG_IP_NF_TARGET_NETMAP_MODULE 1
#define CONFIG_IP_NF_TARGET_SAME_MODULE 1
#define CONFIG_IP_NF_NAT_LOCAL 1
#define CONFIG_IP_NF_NAT_SNMP_BASIC_MODULE 1
#define CONFIG_IP_NF_NAT_IRC_MODULE 1
#define CONFIG_IP_NF_NAT_FTP_MODULE 1
#define CONFIG_IP_NF_NAT_TFTP_MODULE 1
#define CONFIG_IP_NF_NAT_AMANDA_MODULE 1
#define CONFIG_IP_NF_MANGLE_MODULE 1
#define CONFIG_IP_NF_TARGET_TOS_MODULE 1
#define CONFIG_IP_NF_TARGET_ECN_MODULE 1
#define CONFIG_IP_NF_TARGET_DSCP_MODULE 1
#define CONFIG_IP_NF_TARGET_MARK_MODULE 1
#define CONFIG_IP_NF_TARGET_CLASSIFY_MODULE 1
#define CONFIG_IP_NF_TARGET_LOG_MODULE 1
#define CONFIG_IP_NF_TARGET_ULOG_MODULE 1
#define CONFIG_IP_NF_TARGET_TCPMSS_MODULE 1
#define CONFIG_IP_NF_ARPTABLES_MODULE 1
#define CONFIG_IP_NF_ARPFILTER_MODULE 1
#define CONFIG_IP_NF_ARP_MANGLE_MODULE 1
#undef CONFIG_IP_NF_COMPAT_IPCHAINS
#undef CONFIG_IP_NF_COMPAT_IPFWADM
#define CONFIG_IP_NF_TARGET_NOTRACK_MODULE 1
#define CONFIG_IP_NF_RAW_MODULE 1

/*
 * IPv6: Netfilter Configuration
 */
#undef CONFIG_IP6_NF_QUEUE
#define CONFIG_IP6_NF_IPTABLES_MODULE 1
#define CONFIG_IP6_NF_MATCH_LIMIT_MODULE 1
#define CONFIG_IP6_NF_MATCH_MAC_MODULE 1
#define CONFIG_IP6_NF_MATCH_RT_MODULE 1
#define CONFIG_IP6_NF_MATCH_OPTS_MODULE 1
#define CONFIG_IP6_NF_MATCH_FRAG_MODULE 1
#define CONFIG_IP6_NF_MATCH_HL_MODULE 1
#define CONFIG_IP6_NF_MATCH_MULTIPORT_MODULE 1
#define CONFIG_IP6_NF_MATCH_OWNER_MODULE 1
#define CONFIG_IP6_NF_MATCH_MARK_MODULE 1
#define CONFIG_IP6_NF_MATCH_IPV6HEADER_MODULE 1
#define CONFIG_IP6_NF_MATCH_AHESP_MODULE 1
#define CONFIG_IP6_NF_MATCH_LENGTH_MODULE 1
#define CONFIG_IP6_NF_MATCH_EUI64_MODULE 1
#define CONFIG_IP6_NF_FILTER_MODULE 1
#define CONFIG_IP6_NF_TARGET_LOG_MODULE 1
#define CONFIG_IP6_NF_MANGLE_MODULE 1
#define CONFIG_IP6_NF_TARGET_MARK_MODULE 1
#define CONFIG_IP6_NF_RAW_MODULE 1

/*
 * Bridge: Netfilter Configuration
 */
#define CONFIG_BRIDGE_NF_EBTABLES_MODULE 1
#define CONFIG_BRIDGE_EBT_BROUTE_MODULE 1
#define CONFIG_BRIDGE_EBT_T_FILTER_MODULE 1
#define CONFIG_BRIDGE_EBT_T_NAT_MODULE 1
#define CONFIG_BRIDGE_EBT_802_3_MODULE 1
#define CONFIG_BRIDGE_EBT_AMONG_MODULE 1
#define CONFIG_BRIDGE_EBT_ARP_MODULE 1
#define CONFIG_BRIDGE_EBT_IP_MODULE 1
#define CONFIG_BRIDGE_EBT_LIMIT_MODULE 1
#define CONFIG_BRIDGE_EBT_MARK_MODULE 1
#define CONFIG_BRIDGE_EBT_PKTTYPE_MODULE 1
#define CONFIG_BRIDGE_EBT_STP_MODULE 1
#define CONFIG_BRIDGE_EBT_VLAN_MODULE 1
#define CONFIG_BRIDGE_EBT_ARPREPLY_MODULE 1
#define CONFIG_BRIDGE_EBT_DNAT_MODULE 1
#define CONFIG_BRIDGE_EBT_MARK_T_MODULE 1
#define CONFIG_BRIDGE_EBT_REDIRECT_MODULE 1
#define CONFIG_BRIDGE_EBT_SNAT_MODULE 1
#define CONFIG_BRIDGE_EBT_LOG_MODULE 1
#define CONFIG_XFRM 1
#define CONFIG_XFRM_USER 1

/*
 * SCTP Configuration (EXPERIMENTAL)
 */
#define CONFIG_IP_SCTP_MODULE 1
#undef CONFIG_SCTP_DBG_MSG
#undef CONFIG_SCTP_DBG_OBJCNT
#undef CONFIG_SCTP_HMAC_NONE
#undef CONFIG_SCTP_HMAC_SHA1
#define CONFIG_SCTP_HMAC_MD5 1
#undef CONFIG_ATM
#define CONFIG_BRIDGE_MODULE 1
#define CONFIG_VLAN_8021Q_MODULE 1
#undef CONFIG_DECNET
#define CONFIG_LLC_MODULE 1
#undef CONFIG_LLC2
#define CONFIG_IPX_MODULE 1
#undef CONFIG_IPX_INTERN
#define CONFIG_ATALK_MODULE 1
#define CONFIG_DEV_APPLETALK 1
#define CONFIG_LTPC_MODULE 1
#define CONFIG_COPS_MODULE 1
#define CONFIG_COPS_DAYNA 1
#define CONFIG_COPS_TANGENT 1
#define CONFIG_IPDDP_MODULE 1
#define CONFIG_IPDDP_ENCAP 1
#define CONFIG_IPDDP_DECAP 1
#undef CONFIG_X25
#undef CONFIG_LAPB
#define CONFIG_NET_DIVERT 1
#undef CONFIG_ECONET
#define CONFIG_WAN_ROUTER_MODULE 1
#undef CONFIG_NET_FASTROUTE
#undef CONFIG_NET_HW_FLOWCONTROL

/*
 * QoS and/or fair queueing
 */
#define CONFIG_NET_SCHED 1
#define CONFIG_NET_SCH_CBQ_MODULE 1
#define CONFIG_NET_SCH_HTB_MODULE 1
#define CONFIG_NET_SCH_HFSC_MODULE 1
#define CONFIG_NET_SCH_CSZ_MODULE 1
#define CONFIG_NET_SCH_PRIO_MODULE 1
#define CONFIG_NET_SCH_RED_MODULE 1
#define CONFIG_NET_SCH_SFQ_MODULE 1
#define CONFIG_NET_SCH_TEQL_MODULE 1
#define CONFIG_NET_SCH_TBF_MODULE 1
#define CONFIG_NET_SCH_GRED_MODULE 1
#define CONFIG_NET_SCH_DSMARK_MODULE 1
#define CONFIG_NET_SCH_DELAY_MODULE 1
#define CONFIG_NET_SCH_INGRESS_MODULE 1
#define CONFIG_NET_QOS 1
#define CONFIG_NET_ESTIMATOR 1
#define CONFIG_NET_CLS 1
#define CONFIG_NET_CLS_TCINDEX_MODULE 1
#define CONFIG_NET_CLS_ROUTE4_MODULE 1
#define CONFIG_NET_CLS_ROUTE 1
#define CONFIG_NET_CLS_FW_MODULE 1
#define CONFIG_NET_CLS_U32_MODULE 1
#define CONFIG_NET_CLS_RSVP_MODULE 1
#define CONFIG_NET_CLS_RSVP6_MODULE 1
#define CONFIG_NET_CLS_POLICE 1

/*
 * Network testing
 */
#undef CONFIG_NET_PKTGEN
#define CONFIG_NETPOLL 1
#undef CONFIG_NETPOLL_RX
#undef CONFIG_NETPOLL_TRAP
#define CONFIG_NET_POLL_CONTROLLER 1
#undef CONFIG_HAMRADIO
#define CONFIG_IRDA_MODULE 1

/*
 * IrDA protocols
 */
#define CONFIG_IRLAN_MODULE 1
#define CONFIG_IRNET_MODULE 1
#define CONFIG_IRCOMM_MODULE 1
#undef CONFIG_IRDA_ULTRA

/*
 * IrDA options
 */
#define CONFIG_IRDA_CACHE_LAST_LSAP 1
#define CONFIG_IRDA_FAST_RR 1
#undef CONFIG_IRDA_DEBUG

/*
 * Infrared-port device drivers
 */

/*
 * SIR device drivers
 */
#define CONFIG_IRTTY_SIR_MODULE 1

/*
 * Dongle support
 */
#define CONFIG_DONGLE 1
#define CONFIG_ESI_DONGLE_MODULE 1
#define CONFIG_ACTISYS_DONGLE_MODULE 1
#define CONFIG_TEKRAM_DONGLE_MODULE 1
#define CONFIG_LITELINK_DONGLE_MODULE 1
#define CONFIG_MA600_DONGLE_MODULE 1
#define CONFIG_GIRBIL_DONGLE_MODULE 1
#define CONFIG_MCP2120_DONGLE_MODULE 1
#define CONFIG_OLD_BELKIN_DONGLE_MODULE 1
#define CONFIG_ACT200L_DONGLE_MODULE 1

/*
 * Old SIR device drivers
 */

/*
 * Old Serial dongle support
 */

/*
 * FIR device drivers
 */
#define CONFIG_USB_IRDA_MODULE 1
#define CONFIG_SIGMATEL_FIR_MODULE 1
#define CONFIG_NSC_FIR_MODULE 1
#undef CONFIG_WINBOND_FIR
#undef CONFIG_TOSHIBA_FIR
#undef CONFIG_SMC_IRCC_FIR
#undef CONFIG_ALI_FIR
#undef CONFIG_VLSI_FIR
#undef CONFIG_VIA_FIR
#define CONFIG_BT_MODULE 1
#define CONFIG_BT_L2CAP_MODULE 1
#define CONFIG_BT_SCO_MODULE 1
#define CONFIG_BT_RFCOMM_MODULE 1
#define CONFIG_BT_RFCOMM_TTY 1
#define CONFIG_BT_BNEP_MODULE 1
#define CONFIG_BT_BNEP_MC_FILTER 1
#define CONFIG_BT_BNEP_PROTO_FILTER 1
#define CONFIG_BT_CMTP_MODULE 1

/*
 * Bluetooth device drivers
 */
#define CONFIG_BT_HCIUSB_MODULE 1
#define CONFIG_BT_HCIUSB_SCO 1
#define CONFIG_BT_HCIUART_MODULE 1
#define CONFIG_BT_HCIUART_H4 1
#define CONFIG_BT_HCIUART_BCSP 1
#define CONFIG_BT_HCIUART_BCSP_TXCRC 1
#define CONFIG_BT_HCIBCM203X_MODULE 1
#define CONFIG_BT_HCIBFUSB_MODULE 1
#define CONFIG_BT_HCIDTL1_MODULE 1
#define CONFIG_BT_HCIBT3C_MODULE 1
#define CONFIG_BT_HCIBLUECARD_MODULE 1
#define CONFIG_BT_HCIBTUART_MODULE 1
#define CONFIG_BT_HCIVHCI_MODULE 1
#define CONFIG_TUX_MODULE 1

/*
 * TUX options
 */
#define CONFIG_TUX_EXTCGI 1
#undef CONFIG_TUX_EXTENDED_LOG
#undef CONFIG_TUX_DEBUG
#define CONFIG_NETDEVICES 1
#define CONFIG_DUMMY_MODULE 1
#define CONFIG_BONDING_MODULE 1
#define CONFIG_EQUALIZER_MODULE 1
#define CONFIG_TUN_MODULE 1
#define CONFIG_ETHERTAP_MODULE 1
#define CONFIG_NET_SB1000_MODULE 1

/*
 * ARCnet devices
 */
#undef CONFIG_ARCNET

/*
 * Ethernet (10 or 100Mbit)
 */
#define CONFIG_NET_ETHERNET 1
#define CONFIG_MII_MODULE 1
#define CONFIG_HAPPYMEAL_MODULE 1
#define CONFIG_SUNGEM_MODULE 1
#define CONFIG_NET_VENDOR_3COM 1
#define CONFIG_EL1_MODULE 1
#define CONFIG_EL2_MODULE 1
#define CONFIG_ELPLUS_MODULE 1
#define CONFIG_EL16_MODULE 1
#define CONFIG_EL3_MODULE 1
#define CONFIG_3C515_MODULE 1
#define CONFIG_VORTEX_MODULE 1
#define CONFIG_TYPHOON_MODULE 1
#define CONFIG_LANCE_MODULE 1
#define CONFIG_NET_VENDOR_SMC 1
#define CONFIG_WD80x3_MODULE 1
#define CONFIG_ULTRA_MODULE 1
#define CONFIG_SMC9194_MODULE 1
#define CONFIG_NET_VENDOR_RACAL 1
#define CONFIG_NI52_MODULE 1
#define CONFIG_NI65_MODULE 1

/*
 * Tulip family network device support
 */
#define CONFIG_NET_TULIP 1
#define CONFIG_DE2104X_MODULE 1
#define CONFIG_TULIP_MODULE 1
#undef CONFIG_TULIP_MWI
#define CONFIG_TULIP_MMIO 1
#undef CONFIG_TULIP_NAPI
#define CONFIG_DE4X5_MODULE 1
#define CONFIG_WINBOND_840_MODULE 1
#define CONFIG_DM9102_MODULE 1
#define CONFIG_PCMCIA_XIRCOM_MODULE 1
#undef CONFIG_AT1700
#define CONFIG_DEPCA_MODULE 1
#define CONFIG_HP100_MODULE 1
#undef CONFIG_NET_ISA
#define CONFIG_NE2000_MODULE 1
#define CONFIG_NET_PCI 1
#define CONFIG_PCNET32_MODULE 1
#define CONFIG_AMD8111_ETH_MODULE 1
#define CONFIG_AMD8111E_NAPI 1
#define CONFIG_ADAPTEC_STARFIRE_MODULE 1
#define CONFIG_ADAPTEC_STARFIRE_NAPI 1
#define CONFIG_AC3200_MODULE 1
#define CONFIG_APRICOT_MODULE 1
#define CONFIG_B44_MODULE 1
#define CONFIG_FORCEDETH_MODULE 1
#define CONFIG_CS89x0_MODULE 1
#define CONFIG_DGRS_MODULE 1
#define CONFIG_EEPRO100_MODULE 1
#undef CONFIG_EEPRO100_PIO
#define CONFIG_E100_MODULE 1
#define CONFIG_E100_NAPI 1
#define CONFIG_FEALNX_MODULE 1
#define CONFIG_NATSEMI_MODULE 1
#define CONFIG_NE2K_PCI_MODULE 1
#define CONFIG_8139CP_MODULE 1
#define CONFIG_8139TOO_MODULE 1
#define CONFIG_8139TOO_PIO 1
#undef CONFIG_8139TOO_TUNE_TWISTER
#define CONFIG_8139TOO_8129 1
#undef CONFIG_8139_OLD_RX_RESET
#define CONFIG_SIS900_MODULE 1
#define CONFIG_EPIC100_MODULE 1
#define CONFIG_SUNDANCE_MODULE 1
#undef CONFIG_SUNDANCE_MMIO
#define CONFIG_TLAN_MODULE 1
#define CONFIG_VIA_RHINE_MODULE 1
#define CONFIG_VIA_RHINE_MMIO 1
#define CONFIG_NET_POCKET 1
#define CONFIG_ATP_MODULE 1
#define CONFIG_DE600_MODULE 1
#define CONFIG_DE620_MODULE 1

/*
 * Gigabit Ethernet (1000/10000 Mbit)
 */
#define CONFIG_NET_GIGE 1
#define CONFIG_ACENIC_MODULE 1
#undef CONFIG_ACENIC_OMIT_TIGON_I
#define CONFIG_DL2K_MODULE 1
#define CONFIG_E1000_MODULE 1
#define CONFIG_E1000_NAPI 1
#define CONFIG_NS83820_MODULE 1
#define CONFIG_HAMACHI_MODULE 1
#define CONFIG_YELLOWFIN_MODULE 1
#define CONFIG_R8169_MODULE 1
#define CONFIG_SK98LIN_MODULE 1
#define CONFIG_TIGON3_MODULE 1
#define CONFIG_IXGB_MODULE 1
#define CONFIG_IXGB_NAPI 1
#define CONFIG_S2IO_MODULE 1
#define CONFIG_S2IO_NAPI 1

/*
 * Token Ring devices
 */
#undef CONFIG_TR

/*
 * Wireless LAN (non-hamradio)
 */
#define CONFIG_NET_RADIO 1

/*
 * Obsolete Wireless cards support (pre-802.11)
 */
#undef CONFIG_STRIP
#undef CONFIG_ARLAN
#define CONFIG_WAVELAN_MODULE 1
#define CONFIG_PCMCIA_WAVELAN_MODULE 1
#define CONFIG_PCMCIA_NETWAVE_MODULE 1

/*
 * Wireless 802.11 Frequency Hopping cards support
 */
#undef CONFIG_PCMCIA_RAYCS

/*
 * Wireless 802.11b ISA/PCI cards support
 */
#define CONFIG_AIRO_MODULE 1
#define CONFIG_HERMES_MODULE 1
#define CONFIG_PLX_HERMES_MODULE 1
#define CONFIG_TMD_HERMES_MODULE 1
#define CONFIG_PCI_HERMES_MODULE 1
#define CONFIG_ATMEL_MODULE 1
#define CONFIG_PCI_ATMEL_MODULE 1

/*
 * Wireless 802.11b Pcmcia/Cardbus cards support
 */
#define CONFIG_PCMCIA_HERMES_MODULE 1
#define CONFIG_AIRO_CS_MODULE 1
#define CONFIG_PCMCIA_ATMEL_MODULE 1
#define CONFIG_PCMCIA_WL3501_MODULE 1

/*
 * Prism GT/Duette 802.11(a/b/g) PCI/Cardbus support
 */
#define CONFIG_PRISM54_MODULE 1
#define CONFIG_NET_WIRELESS 1

/*
 * PCMCIA network device support
 */
#define CONFIG_NET_PCMCIA 1
#define CONFIG_PCMCIA_3C589_MODULE 1
#define CONFIG_PCMCIA_3C574_MODULE 1
#define CONFIG_PCMCIA_FMVJ18X_MODULE 1
#define CONFIG_PCMCIA_PCNET_MODULE 1
#define CONFIG_PCMCIA_NMCLAN_MODULE 1
#define CONFIG_PCMCIA_SMC91C92_MODULE 1
#define CONFIG_PCMCIA_XIRC2PS_MODULE 1
#define CONFIG_PCMCIA_AXNET_MODULE 1

/*
 * Wan interfaces
 */
#undef CONFIG_WAN
#define CONFIG_FDDI 1
#undef CONFIG_DEFXX
#define CONFIG_SKFP_MODULE 1
#undef CONFIG_HIPPI
#define CONFIG_PLIP_MODULE 1
#define CONFIG_PPP_MODULE 1
#define CONFIG_PPP_MULTILINK 1
#define CONFIG_PPP_FILTER 1
#define CONFIG_PPP_ASYNC_MODULE 1
#define CONFIG_PPP_SYNC_TTY_MODULE 1
#define CONFIG_PPP_DEFLATE_MODULE 1
#undef CONFIG_PPP_BSDCOMP
#define CONFIG_PPPOE_MODULE 1
#undef CONFIG_SLIP
#define CONFIG_NET_FC 1
#undef CONFIG_SHAPER
#define CONFIG_NETCONSOLE_MODULE 1

/*
 * ISDN subsystem
 */
#define CONFIG_ISDN_MODULE 1

/*
 * Old ISDN4Linux
 */
#define CONFIG_ISDN_I4L_MODULE 1
#define CONFIG_ISDN_PPP 1
#define CONFIG_ISDN_PPP_VJ 1
#define CONFIG_ISDN_MPP 1
#define CONFIG_IPPP_FILTER 1
#undef CONFIG_ISDN_PPP_BSDCOMP
#define CONFIG_ISDN_AUDIO 1
#define CONFIG_ISDN_TTY_FAX 1

/*
 * ISDN feature submodules
 */

/*
 * ISDN4Linux hardware drivers
 */

/*
 * Passive cards
 */
#define CONFIG_ISDN_DRV_HISAX_MODULE 1

/*
 * D-channel protocol features
 */
#define CONFIG_HISAX_EURO 1
#define CONFIG_DE_AOC 1
#define CONFIG_HISAX_NO_SENDCOMPLETE 1
#define CONFIG_HISAX_NO_LLC 1
#define CONFIG_HISAX_NO_KEYPAD 1
#define CONFIG_HISAX_1TR6 1
#define CONFIG_HISAX_NI1 1
#define CONFIG_HISAX_MAX_CARDS 8

/*
 * HiSax supported cards
 */
#define CONFIG_HISAX_16_0 1
#define CONFIG_HISAX_16_3 1
#define CONFIG_HISAX_TELESPCI 1
#define CONFIG_HISAX_S0BOX 1
#define CONFIG_HISAX_AVM_A1 1
#define CONFIG_HISAX_FRITZPCI 1
#define CONFIG_HISAX_AVM_A1_PCMCIA 1
#define CONFIG_HISAX_ELSA 1
#define CONFIG_HISAX_IX1MICROR2 1
#define CONFIG_HISAX_DIEHLDIVA 1
#define CONFIG_HISAX_ASUSCOM 1
#define CONFIG_HISAX_TELEINT 1
#define CONFIG_HISAX_HFCS 1
#define CONFIG_HISAX_SEDLBAUER 1
#define CONFIG_HISAX_SPORTSTER 1
#define CONFIG_HISAX_MIC 1
#define CONFIG_HISAX_NETJET 1
#define CONFIG_HISAX_NETJET_U 1
#define CONFIG_HISAX_NICCY 1
#define CONFIG_HISAX_ISURF 1
#define CONFIG_HISAX_HSTSAPHIR 1
#define CONFIG_HISAX_BKM_A4T 1
#define CONFIG_HISAX_SCT_QUADRO 1
#define CONFIG_HISAX_GAZEL 1
#define CONFIG_HISAX_HFC_PCI 1
#define CONFIG_HISAX_W6692 1
#define CONFIG_HISAX_HFC_SX 1
#define CONFIG_HISAX_ENTERNOW_PCI 1
#undef CONFIG_HISAX_DEBUG

/*
 * HiSax PCMCIA card service modules
 */
#define CONFIG_HISAX_SEDLBAUER_CS_MODULE 1
#define CONFIG_HISAX_ELSA_CS_MODULE 1
#define CONFIG_HISAX_AVM_A1_CS_MODULE 1
#define CONFIG_HISAX_TELES_CS_MODULE 1

/*
 * HiSax sub driver modules
 */
#define CONFIG_HISAX_ST5481_MODULE 1
#define CONFIG_HISAX_HFCUSB_MODULE 1
#define CONFIG_HISAX_FRITZ_PCIPNP_MODULE 1
#define CONFIG_HISAX_HDLC 1

/*
 * Active cards
 */
#define CONFIG_ISDN_DRV_ICN_MODULE 1
#define CONFIG_ISDN_DRV_PCBIT_MODULE 1
#define CONFIG_ISDN_DRV_SC_MODULE 1
#define CONFIG_ISDN_DRV_ACT2000_MODULE 1
#define CONFIG_ISDN_DRV_TPAM_MODULE 1

/*
 * CAPI subsystem
 */
#define CONFIG_ISDN_CAPI_MODULE 1
#define CONFIG_ISDN_DRV_AVMB1_VERBOSE_REASON 1
#define CONFIG_ISDN_CAPI_MIDDLEWARE 1
#define CONFIG_ISDN_CAPI_CAPI20_MODULE 1
#define CONFIG_ISDN_CAPI_CAPIFS_BOOL 1
#define CONFIG_ISDN_CAPI_CAPIFS_MODULE 1
#define CONFIG_ISDN_CAPI_CAPIDRV_MODULE 1

/*
 * CAPI hardware drivers
 */

/*
 * Active AVM cards
 */
#define CONFIG_CAPI_AVM 1

/*
 * Active Eicon DIVA Server cards
 */
#define CONFIG_CAPI_EICON 1
#define CONFIG_ISDN_DIVAS_MODULE 1
#define CONFIG_ISDN_DIVAS_BRIPCI 1
#define CONFIG_ISDN_DIVAS_PRIPCI 1
#define CONFIG_ISDN_DIVAS_DIVACAPI_MODULE 1
#define CONFIG_ISDN_DIVAS_USERIDI_MODULE 1
#define CONFIG_ISDN_DIVAS_MAINT_MODULE 1

/*
 * Telephony Support
 */
#undef CONFIG_PHONE

/*
 * Input device support
 */
#define CONFIG_INPUT 1

/*
 * Userland interfaces
 */
#define CONFIG_INPUT_MOUSEDEV 1
#undef CONFIG_INPUT_MOUSEDEV_PSAUX
#define CONFIG_INPUT_MOUSEDEV_SCREEN_X 1024
#define CONFIG_INPUT_MOUSEDEV_SCREEN_Y 768
#define CONFIG_INPUT_JOYDEV_MODULE 1
#undef CONFIG_INPUT_TSDEV
#define CONFIG_INPUT_EVDEV 1
#undef CONFIG_INPUT_EVBUG

/*
 * Input I/O drivers
 */
#define CONFIG_GAMEPORT_MODULE 1
#define CONFIG_SOUND_GAMEPORT_MODULE 1
#define CONFIG_GAMEPORT_NS558_MODULE 1
#define CONFIG_GAMEPORT_L4_MODULE 1
#define CONFIG_GAMEPORT_EMU10K1_MODULE 1
#define CONFIG_GAMEPORT_VORTEX_MODULE 1
#define CONFIG_GAMEPORT_FM801_MODULE 1
#define CONFIG_GAMEPORT_CS461x_MODULE 1
#define CONFIG_SERIO 1
#define CONFIG_SERIO_I8042 1
#define CONFIG_SERIO_SERPORT 1
#undef CONFIG_SERIO_CT82C710
#undef CONFIG_SERIO_PARKBD
#undef CONFIG_SERIO_PCIPS2

/*
 * Input Device Drivers
 */
#define CONFIG_INPUT_KEYBOARD 1
#define CONFIG_KEYBOARD_ATKBD 1
#undef CONFIG_KEYBOARD_SUNKBD
#undef CONFIG_KEYBOARD_LKKBD
#undef CONFIG_KEYBOARD_XTKBD
#undef CONFIG_KEYBOARD_NEWTON
#define CONFIG_INPUT_MOUSE 1
#define CONFIG_MOUSE_PS2 1
#define CONFIG_MOUSE_SERIAL_MODULE 1
#define CONFIG_MOUSE_INPORT_MODULE 1
#define CONFIG_MOUSE_ATIXL 1
#define CONFIG_MOUSE_LOGIBM_MODULE 1
#define CONFIG_MOUSE_PC110PAD_MODULE 1
#define CONFIG_MOUSE_VSXXXAA_MODULE 1
#define CONFIG_INPUT_JOYSTICK 1
#define CONFIG_JOYSTICK_ANALOG_MODULE 1
#define CONFIG_JOYSTICK_A3D_MODULE 1
#define CONFIG_JOYSTICK_ADI_MODULE 1
#define CONFIG_JOYSTICK_COBRA_MODULE 1
#define CONFIG_JOYSTICK_GF2K_MODULE 1
#define CONFIG_JOYSTICK_GRIP_MODULE 1
#define CONFIG_JOYSTICK_GRIP_MP_MODULE 1
#define CONFIG_JOYSTICK_GUILLEMOT_MODULE 1
#define CONFIG_JOYSTICK_INTERACT_MODULE 1
#define CONFIG_JOYSTICK_SIDEWINDER_MODULE 1
#define CONFIG_JOYSTICK_TMDC_MODULE 1
#define CONFIG_JOYSTICK_IFORCE_MODULE 1
#define CONFIG_JOYSTICK_IFORCE_USB 1
#define CONFIG_JOYSTICK_IFORCE_232 1
#define CONFIG_JOYSTICK_WARRIOR_MODULE 1
#define CONFIG_JOYSTICK_MAGELLAN_MODULE 1
#define CONFIG_JOYSTICK_SPACEORB_MODULE 1
#define CONFIG_JOYSTICK_SPACEBALL_MODULE 1
#define CONFIG_JOYSTICK_STINGER_MODULE 1
#define CONFIG_JOYSTICK_TWIDDLER_MODULE 1
#define CONFIG_JOYSTICK_DB9_MODULE 1
#define CONFIG_JOYSTICK_GAMECON_MODULE 1
#define CONFIG_JOYSTICK_TURBOGRAFX_MODULE 1
#undef CONFIG_INPUT_JOYDUMP
#define CONFIG_INPUT_TOUCHSCREEN 1
#define CONFIG_TOUCHSCREEN_GUNZE_MODULE 1
#define CONFIG_INPUT_MISC 1
#define CONFIG_INPUT_PCSPKR_MODULE 1
#undef CONFIG_INPUT_UINPUT

/*
 * Character devices
 */
#define CONFIG_VT 1
#define CONFIG_VT_CONSOLE 1
#define CONFIG_HW_CONSOLE 1
#define CONFIG_SERIAL_NONSTANDARD 1
#define CONFIG_ROCKETPORT_MODULE 1
#undef CONFIG_CYCLADES
#define CONFIG_SYNCLINK_MODULE 1
#define CONFIG_SYNCLINKMP_MODULE 1
#define CONFIG_N_HDLC_MODULE 1
#define CONFIG_STALDRV 1

/*
 * Serial drivers
 */
#define CONFIG_SERIAL_8250 1
#define CONFIG_SERIAL_8250_CONSOLE 1
#define CONFIG_SERIAL_8250_CS_MODULE 1
#undef CONFIG_SERIAL_8250_ACPI
#define CONFIG_SERIAL_8250_NR_UARTS 4
#define CONFIG_SERIAL_8250_EXTENDED 1
#undef CONFIG_SERIAL_8250_MANY_PORTS
#define CONFIG_SERIAL_8250_SHARE_IRQ 1
#define CONFIG_SERIAL_8250_DETECT_IRQ 1
#define CONFIG_SERIAL_8250_MULTIPORT 1
#define CONFIG_SERIAL_8250_RSA 1

/*
 * Non-8250 serial port support
 */
#define CONFIG_SERIAL_CORE 1
#define CONFIG_SERIAL_CORE_CONSOLE 1
#define CONFIG_UNIX98_PTYS 1
#undef CONFIG_LEGACY_PTYS
#define CONFIG_CRASH_MODULE 1
#define CONFIG_PRINTER_MODULE 1
#define CONFIG_LP_CONSOLE 1
#define CONFIG_PPDEV_MODULE 1
#define CONFIG_TIPAR_MODULE 1
#undef CONFIG_QIC02_TAPE

/*
 * IPMI
 */
#define CONFIG_IPMI_HANDLER_MODULE 1
#undef CONFIG_IPMI_PANIC_EVENT
#define CONFIG_IPMI_DEVICE_INTERFACE_MODULE 1
#define CONFIG_IPMI_SI_MODULE 1
#define CONFIG_IPMI_WATCHDOG_MODULE 1

/*
 * Watchdog Cards
 */
#define CONFIG_WATCHDOG 1
#undef CONFIG_WATCHDOG_NOWAYOUT

/*
 * Watchdog Device Drivers
 */
#define CONFIG_SOFT_WATCHDOG_MODULE 1
#define CONFIG_ACQUIRE_WDT_MODULE 1
#define CONFIG_ADVANTECH_WDT_MODULE 1
#define CONFIG_ALIM1535_WDT_MODULE 1
#define CONFIG_ALIM7101_WDT_MODULE 1
#define CONFIG_SC520_WDT_MODULE 1
#define CONFIG_EUROTECH_WDT_MODULE 1
#define CONFIG_IB700_WDT_MODULE 1
#define CONFIG_WAFER_WDT_MODULE 1
#define CONFIG_I8XX_TCO_MODULE 1
#define CONFIG_SC1200_WDT_MODULE 1
#undef CONFIG_SCx200_WDT
#undef CONFIG_60XX_WDT
#define CONFIG_CPU5_WDT_MODULE 1
#define CONFIG_W83627HF_WDT_MODULE 1
#define CONFIG_W83877F_WDT_MODULE 1
#define CONFIG_MACHZ_WDT_MODULE 1

/*
 * ISA-based Watchdog Cards
 */
#define CONFIG_PCWATCHDOG_MODULE 1
#undef CONFIG_MIXCOMWD
#define CONFIG_WDT_MODULE 1
#undef CONFIG_WDT_501

/*
 * PCI-based Watchdog Cards
 */
#define CONFIG_PCIPCWATCHDOG_MODULE 1
#define CONFIG_WDTPCI_MODULE 1
#define CONFIG_WDT_501_PCI 1

/*
 * USB-based Watchdog Cards
 */
#define CONFIG_USBPCWATCHDOG_MODULE 1
#define CONFIG_HW_RANDOM_MODULE 1
#define CONFIG_NVRAM_MODULE 1
#define CONFIG_RTC 1
#define CONFIG_DTLK_MODULE 1
#define CONFIG_R3964_MODULE 1
#undef CONFIG_APPLICOM
#define CONFIG_SONYPI_MODULE 1

/*
 * Ftape, the floppy tape device driver
 */
#define CONFIG_AGP 1
#define CONFIG_AGP_ALI 1
#define CONFIG_AGP_ATI 1
#define CONFIG_AGP_AMD 1
#define CONFIG_AGP_AMD64 1
#define CONFIG_AGP_INTEL 1
#define CONFIG_AGP_INTEL_MCH 1
#define CONFIG_AGP_NVIDIA 1
#define CONFIG_AGP_SIS 1
#define CONFIG_AGP_SWORKS 1
#define CONFIG_AGP_VIA 1
#define CONFIG_AGP_EFFICEON 1
#define CONFIG_DRM 1
#define CONFIG_DRM_TDFX_MODULE 1
#define CONFIG_DRM_GAMMA_MODULE 1
#define CONFIG_DRM_R128_MODULE 1
#define CONFIG_DRM_RADEON_MODULE 1
#define CONFIG_DRM_I810_MODULE 1
#define CONFIG_DRM_I830_MODULE 1
#define CONFIG_DRM_MGA_MODULE 1
#define CONFIG_DRM_SIS_MODULE 1

/*
 * PCMCIA character devices
 */
#define CONFIG_SYNCLINK_CS_MODULE 1
#define CONFIG_MWAVE_MODULE 1
#undef CONFIG_RAW_DRIVER
#define CONFIG_HANGCHECK_TIMER_MODULE 1

/*
 * I2C support
 */
#define CONFIG_I2C_MODULE 1
#define CONFIG_I2C_CHARDEV_MODULE 1

/*
 * I2C Algorithms
 */
#define CONFIG_I2C_ALGOBIT_MODULE 1
#define CONFIG_I2C_ALGOPCF_MODULE 1

/*
 * I2C Hardware Bus support
 */
#define CONFIG_I2C_ALI1535_MODULE 1
#define CONFIG_I2C_ALI1563_MODULE 1
#define CONFIG_I2C_ALI15X3_MODULE 1
#define CONFIG_I2C_AMD756_MODULE 1
#define CONFIG_I2C_AMD8111_MODULE 1
#define CONFIG_I2C_I801_MODULE 1
#define CONFIG_I2C_I810_MODULE 1
#define CONFIG_I2C_ISA_MODULE 1
#define CONFIG_I2C_NFORCE2_MODULE 1
#undef CONFIG_I2C_PARPORT
#undef CONFIG_I2C_PARPORT_LIGHT
#define CONFIG_I2C_PIIX4_MODULE 1
#define CONFIG_I2C_PROSAVAGE_MODULE 1
#define CONFIG_I2C_SAVAGE4_MODULE 1
#undef CONFIG_SCx200_ACB
#define CONFIG_I2C_SIS5595_MODULE 1
#define CONFIG_I2C_SIS630_MODULE 1
#define CONFIG_I2C_SIS96X_MODULE 1
#define CONFIG_I2C_VIA_MODULE 1
#define CONFIG_I2C_VIAPRO_MODULE 1
#define CONFIG_I2C_VOODOO3_MODULE 1

/*
 * Hardware Sensors Chip support
 */
#define CONFIG_I2C_SENSOR_MODULE 1
#define CONFIG_SENSORS_ADM1021_MODULE 1
#define CONFIG_SENSORS_ASB100_MODULE 1
#define CONFIG_SENSORS_DS1621_MODULE 1
#define CONFIG_SENSORS_FSCHER_MODULE 1
#define CONFIG_SENSORS_GL518SM_MODULE 1
#define CONFIG_SENSORS_IT87_MODULE 1
#define CONFIG_SENSORS_LM75_MODULE 1
#define CONFIG_SENSORS_LM78_MODULE 1
#define CONFIG_SENSORS_LM80_MODULE 1
#define CONFIG_SENSORS_LM83_MODULE 1
#define CONFIG_SENSORS_LM85_MODULE 1
#define CONFIG_SENSORS_LM90_MODULE 1
#define CONFIG_SENSORS_MAX1619_MODULE 1
#define CONFIG_SENSORS_VIA686A_MODULE 1
#define CONFIG_SENSORS_W83781D_MODULE 1
#define CONFIG_SENSORS_W83L785TS_MODULE 1
#define CONFIG_SENSORS_W83627HF_MODULE 1

/*
 * Other I2C Chip support
 */
#define CONFIG_SENSORS_EEPROM_MODULE 1
#define CONFIG_SENSORS_PCF8574_MODULE 1
#define CONFIG_SENSORS_PCF8591_MODULE 1
#define CONFIG_SENSORS_RTC8564_MODULE 1
#undef CONFIG_I2C_DEBUG_CORE
#undef CONFIG_I2C_DEBUG_ALGO
#undef CONFIG_I2C_DEBUG_BUS
#undef CONFIG_I2C_DEBUG_CHIP

/*
 * Misc devices
 */
#define CONFIG_IBM_ASM_MODULE 1

/*
 * Multimedia devices
 */
#define CONFIG_VIDEO_DEV_MODULE 1

/*
 * Video For Linux
 */

/*
 * Video Adapters
 */
#define CONFIG_VIDEO_BT848_MODULE 1
#define CONFIG_VIDEO_PMS_MODULE 1
#define CONFIG_VIDEO_BWQCAM_MODULE 1
#define CONFIG_VIDEO_CQCAM_MODULE 1
#define CONFIG_VIDEO_W9966_MODULE 1
#define CONFIG_VIDEO_CPIA_MODULE 1
#define CONFIG_VIDEO_CPIA_PP_MODULE 1
#define CONFIG_VIDEO_CPIA_USB_MODULE 1
#define CONFIG_VIDEO_SAA5246A_MODULE 1
#define CONFIG_VIDEO_SAA5249_MODULE 1
#define CONFIG_TUNER_3036_MODULE 1
#define CONFIG_VIDEO_STRADIS_MODULE 1
#define CONFIG_VIDEO_ZORAN_MODULE 1
#define CONFIG_VIDEO_ZORAN_BUZ_MODULE 1
#define CONFIG_VIDEO_ZORAN_DC10_MODULE 1
#define CONFIG_VIDEO_ZORAN_DC30_MODULE 1
#define CONFIG_VIDEO_ZORAN_LML33_MODULE 1
#define CONFIG_VIDEO_ZORAN_LML33R10_MODULE 1
#define CONFIG_VIDEO_SAA7134_MODULE 1
#define CONFIG_VIDEO_MXB_MODULE 1
#define CONFIG_VIDEO_DPC_MODULE 1
#define CONFIG_VIDEO_HEXIUM_ORION_MODULE 1
#define CONFIG_VIDEO_HEXIUM_GEMINI_MODULE 1
#define CONFIG_VIDEO_CX88_MODULE 1

/*
 * Radio Adapters
 */
#define CONFIG_RADIO_CADET_MODULE 1
#define CONFIG_RADIO_RTRACK_MODULE 1
#define CONFIG_RADIO_RTRACK2_MODULE 1
#define CONFIG_RADIO_AZTECH_MODULE 1
#define CONFIG_RADIO_GEMTEK_MODULE 1
#define CONFIG_RADIO_GEMTEK_PCI_MODULE 1
#define CONFIG_RADIO_MAXIRADIO_MODULE 1
#define CONFIG_RADIO_MAESTRO_MODULE 1
#define CONFIG_RADIO_SF16FMI_MODULE 1
#define CONFIG_RADIO_SF16FMR2_MODULE 1
#define CONFIG_RADIO_TERRATEC_MODULE 1
#define CONFIG_RADIO_TRUST_MODULE 1
#define CONFIG_RADIO_TYPHOON_MODULE 1
#define CONFIG_RADIO_TYPHOON_PROC_FS 1
#define CONFIG_RADIO_ZOLTRIX_MODULE 1

/*
 * Digital Video Broadcasting Devices
 */
#undef CONFIG_DVB
#define CONFIG_VIDEO_SAA7146_MODULE 1
#define CONFIG_VIDEO_SAA7146_VV_MODULE 1
#define CONFIG_VIDEO_VIDEOBUF_MODULE 1
#define CONFIG_VIDEO_TUNER_MODULE 1
#define CONFIG_VIDEO_BUF_MODULE 1
#define CONFIG_VIDEO_BTCX_MODULE 1
#define CONFIG_VIDEO_IR_MODULE 1

/*
 * Graphics support
 */
#define CONFIG_FB 1
#undef CONFIG_FB_PM2
#undef CONFIG_FB_CYBER2000
#undef CONFIG_FB_ASILIANT
#undef CONFIG_FB_IMSTT
#define CONFIG_FB_VGA16_MODULE 1
#define CONFIG_FB_VESA 1
#define CONFIG_VIDEO_SELECT 1
#define CONFIG_FB_HGA_MODULE 1
#define CONFIG_FB_HGA_ACCEL 1
#define CONFIG_FB_RIVA_MODULE 1
#define CONFIG_FB_I810_MODULE 1
#define CONFIG_FB_I810_GTF 1
#define CONFIG_FB_MATROX_MODULE 1
#define CONFIG_FB_MATROX_MILLENIUM 1
#define CONFIG_FB_MATROX_MYSTIQUE 1
#define CONFIG_FB_MATROX_G450 1
#define CONFIG_FB_MATROX_G100 1
#define CONFIG_FB_MATROX_I2C_MODULE 1
#define CONFIG_FB_MATROX_MAVEN_MODULE 1
#define CONFIG_FB_MATROX_MULTIHEAD 1
#undef CONFIG_FB_RADEON_OLD
#define CONFIG_FB_RADEON_MODULE 1
#define CONFIG_FB_RADEON_I2C 1
#undef CONFIG_FB_RADEON_DEBUG
#define CONFIG_FB_ATY128_MODULE 1
#define CONFIG_FB_ATY_MODULE 1
#define CONFIG_FB_ATY_CT 1
#define CONFIG_FB_ATY_GX 1
#undef CONFIG_FB_ATY_XL_INIT
#undef CONFIG_FB_SIS
#define CONFIG_FB_NEOMAGIC_MODULE 1
#define CONFIG_FB_KYRO_MODULE 1
#define CONFIG_FB_3DFX_MODULE 1
#define CONFIG_FB_3DFX_ACCEL 1
#define CONFIG_FB_VOODOO1_MODULE 1
#define CONFIG_FB_TRIDENT_MODULE 1
#define CONFIG_FB_TRIDENT_ACCEL 1
#undef CONFIG_FB_VIRTUAL

/*
 * Console display driver support
 */
#define CONFIG_VGA_CONSOLE 1
#define CONFIG_MDA_CONSOLE_MODULE 1
#define CONFIG_DUMMY_CONSOLE 1
#define CONFIG_FRAMEBUFFER_CONSOLE 1
#define CONFIG_PCI_CONSOLE 1
#undef CONFIG_FONTS
#define CONFIG_FONT_8x8 1
#define CONFIG_FONT_8x16 1

/*
 * Logo configuration
 */
#define CONFIG_LOGO 1
#undef CONFIG_LOGO_LINUX_MONO
#undef CONFIG_LOGO_LINUX_VGA16
#define CONFIG_LOGO_LINUX_CLUT224 1

/*
 * Sound
 */
#define CONFIG_SOUND_MODULE 1

/*
 * Advanced Linux Sound Architecture
 */
#define CONFIG_SND_MODULE 1
#define CONFIG_SND_TIMER_MODULE 1
#define CONFIG_SND_PCM_MODULE 1
#define CONFIG_SND_HWDEP_MODULE 1
#define CONFIG_SND_RAWMIDI_MODULE 1
#define CONFIG_SND_SEQUENCER_MODULE 1
#define CONFIG_SND_SEQ_DUMMY_MODULE 1
#define CONFIG_SND_OSSEMUL 1
#define CONFIG_SND_MIXER_OSS_MODULE 1
#define CONFIG_SND_PCM_OSS_MODULE 1
#define CONFIG_SND_SEQUENCER_OSS 1
#define CONFIG_SND_RTCTIMER_MODULE 1
#undef CONFIG_SND_VERBOSE_PRINTK
#undef CONFIG_SND_DEBUG

/*
 * Generic devices
 */
#define CONFIG_SND_MPU401_UART_MODULE 1
#define CONFIG_SND_OPL3_LIB_MODULE 1
#define CONFIG_SND_OPL4_LIB_MODULE 1
#define CONFIG_SND_VX_LIB_MODULE 1
#define CONFIG_SND_DUMMY_MODULE 1
#define CONFIG_SND_VIRMIDI_MODULE 1
#define CONFIG_SND_MTPAV_MODULE 1
#undef CONFIG_SND_SERIAL_U16550
#define CONFIG_SND_MPU401_MODULE 1

/*
 * ISA devices
 */
#define CONFIG_SND_AD1816A_MODULE 1
#define CONFIG_SND_AD1848_MODULE 1
#define CONFIG_SND_CS4231_MODULE 1
#define CONFIG_SND_CS4232_MODULE 1
#define CONFIG_SND_CS4236_MODULE 1
#define CONFIG_SND_ES968_MODULE 1
#define CONFIG_SND_ES1688_MODULE 1
#define CONFIG_SND_ES18XX_MODULE 1
#define CONFIG_SND_GUSCLASSIC_MODULE 1
#define CONFIG_SND_GUSEXTREME_MODULE 1
#define CONFIG_SND_GUSMAX_MODULE 1
#define CONFIG_SND_INTERWAVE_MODULE 1
#define CONFIG_SND_INTERWAVE_STB_MODULE 1
#define CONFIG_SND_OPTI92X_AD1848_MODULE 1
#define CONFIG_SND_OPTI92X_CS4231_MODULE 1
#define CONFIG_SND_OPTI93X_MODULE 1
#define CONFIG_SND_SB8_MODULE 1
#define CONFIG_SND_SB16_MODULE 1
#define CONFIG_SND_SBAWE_MODULE 1
#define CONFIG_SND_SB16_CSP 1
#undef CONFIG_SND_WAVEFRONT
#define CONFIG_SND_ALS100_MODULE 1
#define CONFIG_SND_AZT2320_MODULE 1
#define CONFIG_SND_CMI8330_MODULE 1
#define CONFIG_SND_DT019X_MODULE 1
#define CONFIG_SND_OPL3SA2_MODULE 1
#define CONFIG_SND_SGALAXY_MODULE 1
#define CONFIG_SND_SSCAPE_MODULE 1

/*
 * PCI devices
 */
#define CONFIG_SND_AC97_CODEC_MODULE 1
#define CONFIG_SND_ALI5451_MODULE 1
#define CONFIG_SND_ATIIXP_MODULE 1
#define CONFIG_SND_AU8810_MODULE 1
#define CONFIG_SND_AU8820_MODULE 1
#define CONFIG_SND_AU8830_MODULE 1
#define CONFIG_SND_AZT3328_MODULE 1
#define CONFIG_SND_BT87X_MODULE 1
#define CONFIG_SND_CS46XX_MODULE 1
#define CONFIG_SND_CS46XX_NEW_DSP 1
#define CONFIG_SND_CS4281_MODULE 1
#define CONFIG_SND_EMU10K1_MODULE 1
#define CONFIG_SND_KORG1212_MODULE 1
#define CONFIG_SND_MIXART_MODULE 1
#define CONFIG_SND_NM256_MODULE 1
#define CONFIG_SND_RME32_MODULE 1
#define CONFIG_SND_RME96_MODULE 1
#define CONFIG_SND_RME9652_MODULE 1
#define CONFIG_SND_HDSP_MODULE 1
#define CONFIG_SND_TRIDENT_MODULE 1
#define CONFIG_SND_YMFPCI_MODULE 1
#define CONFIG_SND_ALS4000_MODULE 1
#define CONFIG_SND_CMIPCI_MODULE 1
#define CONFIG_SND_ENS1370_MODULE 1
#define CONFIG_SND_ENS1371_MODULE 1
#define CONFIG_SND_ES1938_MODULE 1
#define CONFIG_SND_ES1968_MODULE 1
#define CONFIG_SND_MAESTRO3_MODULE 1
#define CONFIG_SND_FM801_MODULE 1
#define CONFIG_SND_FM801_TEA575X_MODULE 1
#define CONFIG_SND_ICE1712_MODULE 1
#define CONFIG_SND_ICE1724_MODULE 1
#define CONFIG_SND_INTEL8X0_MODULE 1
#define CONFIG_SND_INTEL8X0M_MODULE 1
#define CONFIG_SND_SONICVIBES_MODULE 1
#define CONFIG_SND_VIA82XX_MODULE 1
#define CONFIG_SND_VX222_MODULE 1

/*
 * ALSA USB devices
 */
#define CONFIG_SND_USB_AUDIO_MODULE 1

/*
 * PCMCIA devices
 */
#undef CONFIG_SND_VXPOCKET
#undef CONFIG_SND_VXP440
#define CONFIG_SND_PDAUDIOCF_MODULE 1

/*
 * Open Sound System
 */
#undef CONFIG_SOUND_PRIME

/*
 * USB support
 */
#define CONFIG_USB 1
#undef CONFIG_USB_DEBUG

/*
 * Miscellaneous USB options
 */
#define CONFIG_USB_DEVICEFS 1
#undef CONFIG_USB_BANDWIDTH
#undef CONFIG_USB_DYNAMIC_MINORS

/*
 * USB Host Controller Drivers
 */
#define CONFIG_USB_EHCI_HCD_MODULE 1
#define CONFIG_USB_EHCI_SPLIT_ISO 1
#define CONFIG_USB_EHCI_ROOT_HUB_TT 1
#define CONFIG_USB_OHCI_HCD_MODULE 1
#define CONFIG_USB_UHCI_HCD_MODULE 1

/*
 * USB Device Class drivers
 */
#define CONFIG_USB_AUDIO_MODULE 1

/*
 * USB Bluetooth TTY can only be used with disabled Bluetooth subsystem
 */
#define CONFIG_USB_MIDI_MODULE 1
#define CONFIG_USB_ACM_MODULE 1
#define CONFIG_USB_PRINTER_MODULE 1
#define CONFIG_USB_STORAGE_MODULE 1
#undef CONFIG_USB_STORAGE_DEBUG
#define CONFIG_USB_STORAGE_DATAFAB 1
#define CONFIG_USB_STORAGE_FREECOM 1
#define CONFIG_USB_STORAGE_ISD200 1
#define CONFIG_USB_STORAGE_DPCM 1
#define CONFIG_USB_STORAGE_HP8200e 1
#define CONFIG_USB_STORAGE_SDDR09 1
#define CONFIG_USB_STORAGE_SDDR55 1
#define CONFIG_USB_STORAGE_JUMPSHOT 1

/*
 * USB Human Interface Devices (HID)
 */
#define CONFIG_USB_HID 1
#define CONFIG_USB_HIDINPUT 1
#define CONFIG_HID_FF 1
#define CONFIG_HID_PID 1
#define CONFIG_LOGITECH_FF 1
#define CONFIG_THRUSTMASTER_FF 1
#define CONFIG_USB_HIDDEV 1
#define CONFIG_USB_AIPTEK_MODULE 1
#define CONFIG_USB_WACOM_MODULE 1
#define CONFIG_USB_KBTAB_MODULE 1
#define CONFIG_USB_POWERMATE_MODULE 1
#define CONFIG_USB_MTOUCH_MODULE 1
#define CONFIG_USB_EGALAX_MODULE 1
#define CONFIG_USB_XPAD_MODULE 1
#define CONFIG_USB_ATI_REMOTE_MODULE 1

/*
 * USB Imaging devices
 */
#define CONFIG_USB_MDC800_MODULE 1
#define CONFIG_USB_MICROTEK_MODULE 1
#define CONFIG_USB_HPUSBSCSI_MODULE 1

/*
 * USB Multimedia devices
 */
#define CONFIG_USB_DABUSB_MODULE 1
#define CONFIG_USB_VICAM_MODULE 1
#define CONFIG_USB_DSBR_MODULE 1
#define CONFIG_USB_IBMCAM_MODULE 1
#define CONFIG_USB_KONICAWC_MODULE 1
#define CONFIG_USB_OV511_MODULE 1
#define CONFIG_USB_SE401_MODULE 1
#define CONFIG_USB_STV680_MODULE 1
#define CONFIG_USB_W9968CF_MODULE 1

/*
 * USB Network adaptors
 */
#define CONFIG_USB_CATC_MODULE 1
#define CONFIG_USB_KAWETH_MODULE 1
#define CONFIG_USB_PEGASUS_MODULE 1
#define CONFIG_USB_RTL8150_MODULE 1
#define CONFIG_USB_USBNET_MODULE 1

/*
 * USB Host-to-Host Cables
 */
#define CONFIG_USB_ALI_M5632 1
#define CONFIG_USB_AN2720 1
#define CONFIG_USB_BELKIN 1
#define CONFIG_USB_GENESYS 1
#define CONFIG_USB_NET1080 1
#define CONFIG_USB_PL2301 1

/*
 * Intelligent USB Devices/Gadgets
 */
#define CONFIG_USB_ARMLINUX 1
#define CONFIG_USB_EPSON2888 1
#define CONFIG_USB_ZAURUS 1
#define CONFIG_USB_CDCETHER 1

/*
 * USB Network Adapters
 */
#define CONFIG_USB_AX8817X 1

/*
 * USB port drivers
 */
#define CONFIG_USB_USS720_MODULE 1

/*
 * USB Serial Converter support
 */
#define CONFIG_USB_SERIAL_MODULE 1
#define CONFIG_USB_SERIAL_GENERIC 1
#define CONFIG_USB_SERIAL_BELKIN_MODULE 1
#define CONFIG_USB_SERIAL_DIGI_ACCELEPORT_MODULE 1
#define CONFIG_USB_SERIAL_EMPEG_MODULE 1
#define CONFIG_USB_SERIAL_FTDI_SIO_MODULE 1
#define CONFIG_USB_SERIAL_VISOR_MODULE 1
#define CONFIG_USB_SERIAL_IPAQ_MODULE 1
#define CONFIG_USB_SERIAL_IR_MODULE 1
#define CONFIG_USB_SERIAL_EDGEPORT_MODULE 1
#define CONFIG_USB_SERIAL_EDGEPORT_TI_MODULE 1
#define CONFIG_USB_SERIAL_KEYSPAN_PDA_MODULE 1
#define CONFIG_USB_SERIAL_KEYSPAN_MODULE 1
#define CONFIG_USB_SERIAL_KEYSPAN_MPR 1
#define CONFIG_USB_SERIAL_KEYSPAN_USA28 1
#define CONFIG_USB_SERIAL_KEYSPAN_USA28X 1
#define CONFIG_USB_SERIAL_KEYSPAN_USA28XA 1
#define CONFIG_USB_SERIAL_KEYSPAN_USA28XB 1
#define CONFIG_USB_SERIAL_KEYSPAN_USA19 1
#define CONFIG_USB_SERIAL_KEYSPAN_USA18X 1
#define CONFIG_USB_SERIAL_KEYSPAN_USA19W 1
#define CONFIG_USB_SERIAL_KEYSPAN_USA19QW 1
#define CONFIG_USB_SERIAL_KEYSPAN_USA19QI 1
#define CONFIG_USB_SERIAL_KEYSPAN_USA49W 1
#define CONFIG_USB_SERIAL_KEYSPAN_USA49WLC 1
#define CONFIG_USB_SERIAL_KLSI_MODULE 1
#define CONFIG_USB_SERIAL_KOBIL_SCT_MODULE 1
#define CONFIG_USB_SERIAL_MCT_U232_MODULE 1
#define CONFIG_USB_SERIAL_PL2303_MODULE 1
#define CONFIG_USB_SERIAL_SAFE_MODULE 1
#define CONFIG_USB_SERIAL_SAFE_PADDED 1
#define CONFIG_USB_SERIAL_CYBERJACK_MODULE 1
#define CONFIG_USB_SERIAL_XIRCOM_MODULE 1
#define CONFIG_USB_SERIAL_OMNINET_MODULE 1
#define CONFIG_USB_EZUSB 1

/*
 * USB Miscellaneous drivers
 */
#define CONFIG_USB_EMI62_MODULE 1
#undef CONFIG_USB_EMI26
#define CONFIG_USB_TIGL_MODULE 1
#define CONFIG_USB_AUERSWALD_MODULE 1
#define CONFIG_USB_RIO500_MODULE 1
#define CONFIG_USB_LEGOTOWER_MODULE 1
#define CONFIG_USB_LCD_MODULE 1
#define CONFIG_USB_LED_MODULE 1
#undef CONFIG_USB_CYTHERM
#define CONFIG_USB_PHIDGETSERVO_MODULE 1
#define CONFIG_USB_TEST_MODULE 1

/*
 * USB Gadget Support
 */
#undef CONFIG_USB_GADGET

/*
 * File systems
 */
#define CONFIG_EXT2_FS 1
#define CONFIG_EXT2_FS_XATTR 1
#define CONFIG_EXT2_FS_POSIX_ACL 1
#define CONFIG_EXT2_FS_SECURITY 1
#define CONFIG_EXT3_FS_MODULE 1
#define CONFIG_EXT3_FS_XATTR 1
#define CONFIG_EXT3_FS_POSIX_ACL 1
#define CONFIG_EXT3_FS_SECURITY 1
#define CONFIG_JBD_MODULE 1
#undef CONFIG_JBD_DEBUG
#define CONFIG_FS_MBCACHE 1
#define CONFIG_REISERFS_FS_MODULE 1
#undef CONFIG_REISERFS_CHECK
#define CONFIG_REISERFS_PROC_INFO 1
#define CONFIG_REISERFS_FS_XATTR 1
#define CONFIG_REISERFS_FS_POSIX_ACL 1
#define CONFIG_REISERFS_FS_SECURITY 1
#define CONFIG_JFS_FS_MODULE 1
#define CONFIG_JFS_POSIX_ACL 1
#undef CONFIG_JFS_DEBUG
#undef CONFIG_JFS_STATISTICS
#define CONFIG_FS_POSIX_ACL 1
#define CONFIG_XFS_FS_MODULE 1
#undef CONFIG_XFS_RT
#define CONFIG_XFS_QUOTA 1
#define CONFIG_XFS_SECURITY 1
#define CONFIG_XFS_POSIX_ACL 1
#define CONFIG_MINIX_FS_MODULE 1
#define CONFIG_ROMFS_FS_MODULE 1
#define CONFIG_QUOTA 1
#undef CONFIG_QFMT_V1
#define CONFIG_QFMT_V2 1
#define CONFIG_QUOTACTL 1
#define CONFIG_AUTOFS_FS_MODULE 1
#define CONFIG_AUTOFS4_FS_MODULE 1

/*
 * CD-ROM/DVD Filesystems
 */
#define CONFIG_ISO9660_FS 1
#define CONFIG_JOLIET 1
#define CONFIG_ZISOFS 1
#define CONFIG_ZISOFS_FS 1
#define CONFIG_UDF_FS_MODULE 1

/*
 * DOS/FAT/NT Filesystems
 */
#define CONFIG_FAT_FS_MODULE 1
#define CONFIG_MSDOS_FS_MODULE 1
#define CONFIG_VFAT_FS_MODULE 1
#undef CONFIG_NTFS_FS

/*
 * Pseudo filesystems
 */
#define CONFIG_PROC_FS 1
#define CONFIG_PROC_KCORE 1
#define CONFIG_SYSFS 1
#undef CONFIG_DEVFS_FS
#define CONFIG_DEVPTS_FS_XATTR 1
#define CONFIG_DEVPTS_FS_SECURITY 1
#define CONFIG_TMPFS 1
#define CONFIG_HUGETLBFS 1
#define CONFIG_HUGETLB_PAGE 1
#define CONFIG_RAMFS 1

/*
 * Miscellaneous filesystems
 */
#undef CONFIG_ADFS_FS
#define CONFIG_AFFS_FS_MODULE 1
#define CONFIG_HFS_FS_MODULE 1
#define CONFIG_HFSPLUS_FS_MODULE 1
#define CONFIG_BEFS_FS_MODULE 1
#undef CONFIG_BEFS_DEBUG
#define CONFIG_BFS_FS_MODULE 1
#define CONFIG_EFS_FS_MODULE 1
#undef CONFIG_JFFS_FS
#define CONFIG_JFFS2_FS_MODULE 1
#define CONFIG_JFFS2_FS_DEBUG 0
#define CONFIG_JFFS2_FS_NAND 1
#define CONFIG_CRAMFS_MODULE 1
#define CONFIG_VXFS_FS_MODULE 1
#undef CONFIG_HPFS_FS
#define CONFIG_QNX4FS_FS_MODULE 1
#undef CONFIG_QNX4FS_RW
#define CONFIG_SYSV_FS_MODULE 1
#define CONFIG_UFS_FS_MODULE 1
#undef CONFIG_UFS_FS_WRITE

/*
 * Network File Systems
 */
#define CONFIG_NFS_FS_MODULE 1
#define CONFIG_NFS_V3 1
#define CONFIG_NFS_V4 1
#define CONFIG_NFS_DIRECTIO 1
#define CONFIG_NFSD_MODULE 1
#define CONFIG_NFSD_V3 1
#define CONFIG_NFSD_V4 1
#define CONFIG_NFSD_TCP 1
#define CONFIG_LOCKD_MODULE 1
#define CONFIG_LOCKD_V4 1
#define CONFIG_EXPORTFS_MODULE 1
#define CONFIG_SUNRPC_MODULE 1
#define CONFIG_SUNRPC_GSS_MODULE 1
#define CONFIG_RPCSEC_GSS_KRB5_MODULE 1
#define CONFIG_SMB_FS_MODULE 1
#undef CONFIG_SMB_NLS_DEFAULT
#define CONFIG_CIFS_MODULE 1
#undef CONFIG_CIFS_STATS
#define CONFIG_NCP_FS_MODULE 1
#define CONFIG_NCPFS_PACKET_SIGNING 1
#define CONFIG_NCPFS_IOCTL_LOCKING 1
#define CONFIG_NCPFS_STRONG 1
#define CONFIG_NCPFS_NFS_NS 1
#define CONFIG_NCPFS_OS2_NS 1
#define CONFIG_NCPFS_SMALLDOS 1
#define CONFIG_NCPFS_NLS 1
#define CONFIG_NCPFS_EXTRAS 1
#undef CONFIG_CODA_FS
#undef CONFIG_AFS_FS

/*
 * Partition Types
 */
#define CONFIG_PARTITION_ADVANCED 1
#undef CONFIG_ACORN_PARTITION
#define CONFIG_OSF_PARTITION 1
#undef CONFIG_AMIGA_PARTITION
#undef CONFIG_ATARI_PARTITION
#define CONFIG_MAC_PARTITION 1
#define CONFIG_MSDOS_PARTITION 1
#define CONFIG_BSD_DISKLABEL 1
#define CONFIG_MINIX_SUBPARTITION 1
#define CONFIG_SOLARIS_X86_PARTITION 1
#define CONFIG_UNIXWARE_DISKLABEL 1
#undef CONFIG_LDM_PARTITION
#undef CONFIG_NEC98_PARTITION
#define CONFIG_SGI_PARTITION 1
#undef CONFIG_ULTRIX_PARTITION
#define CONFIG_SUN_PARTITION 1
#define CONFIG_EFI_PARTITION 1

/*
 * Native Language Support
 */
#define CONFIG_NLS 1
#define CONFIG_NLS_DEFAULT "utf8"
#define CONFIG_NLS_CODEPAGE_437_MODULE 1
#define CONFIG_NLS_CODEPAGE_737_MODULE 1
#define CONFIG_NLS_CODEPAGE_775_MODULE 1
#define CONFIG_NLS_CODEPAGE_850_MODULE 1
#define CONFIG_NLS_CODEPAGE_852_MODULE 1
#define CONFIG_NLS_CODEPAGE_855_MODULE 1
#define CONFIG_NLS_CODEPAGE_857_MODULE 1
#define CONFIG_NLS_CODEPAGE_860_MODULE 1
#define CONFIG_NLS_CODEPAGE_861_MODULE 1
#define CONFIG_NLS_CODEPAGE_862_MODULE 1
#define CONFIG_NLS_CODEPAGE_863_MODULE 1
#define CONFIG_NLS_CODEPAGE_864_MODULE 1
#define CONFIG_NLS_CODEPAGE_865_MODULE 1
#define CONFIG_NLS_CODEPAGE_866_MODULE 1
#define CONFIG_NLS_CODEPAGE_869_MODULE 1
#define CONFIG_NLS_CODEPAGE_936_MODULE 1
#define CONFIG_NLS_CODEPAGE_950_MODULE 1
#define CONFIG_NLS_CODEPAGE_932_MODULE 1
#define CONFIG_NLS_CODEPAGE_949_MODULE 1
#define CONFIG_NLS_CODEPAGE_874_MODULE 1
#define CONFIG_NLS_ISO8859_8_MODULE 1
#define CONFIG_NLS_CODEPAGE_1250_MODULE 1
#define CONFIG_NLS_CODEPAGE_1251_MODULE 1
#define CONFIG_NLS_ISO8859_1_MODULE 1
#define CONFIG_NLS_ISO8859_2_MODULE 1
#define CONFIG_NLS_ISO8859_3_MODULE 1
#define CONFIG_NLS_ISO8859_4_MODULE 1
#define CONFIG_NLS_ISO8859_5_MODULE 1
#define CONFIG_NLS_ISO8859_6_MODULE 1
#define CONFIG_NLS_ISO8859_7_MODULE 1
#define CONFIG_NLS_ISO8859_9_MODULE 1
#define CONFIG_NLS_ISO8859_13_MODULE 1
#define CONFIG_NLS_ISO8859_14_MODULE 1
#define CONFIG_NLS_ISO8859_15_MODULE 1
#define CONFIG_NLS_KOI8_R_MODULE 1
#define CONFIG_NLS_KOI8_U_MODULE 1
#define CONFIG_NLS_UTF8_MODULE 1

/*
 * Profiling support
 */
#define CONFIG_PROFILING 1
#define CONFIG_OPROFILE_MODULE 1

/*
 * Kernel hacking
 */
#define CONFIG_DEBUG_KERNEL 1
#define CONFIG_EARLY_PRINTK 1
#define CONFIG_DEBUG_STACKOVERFLOW 1
#undef CONFIG_DEBUG_STACK_USAGE
#undef CONFIG_DEBUG_SLAB
#define CONFIG_MAGIC_SYSRQ 1
#undef CONFIG_DEBUG_SPINLOCK
#undef CONFIG_DEBUG_PAGEALLOC
#undef CONFIG_DEBUG_HIGHMEM
#define CONFIG_DEBUG_INFO 1
#define CONFIG_DEBUG_SPINLOCK_SLEEP 1
#undef CONFIG_FRAME_POINTER
#define CONFIG_X86_FIND_SMP_CONFIG 1
#define CONFIG_X86_MPPARSE 1

/*
 * Security options
 */
#define CONFIG_SECURITY 1
#define CONFIG_SECURITY_NETWORK 1
#define CONFIG_SECURITY_CAPABILITIES 1
#undef CONFIG_SECURITY_ROOTPLUG
#define CONFIG_SECURITY_SELINUX 1
#define CONFIG_SECURITY_SELINUX_BOOTPARAM 1
#define CONFIG_SECURITY_SELINUX_DISABLE 1
#define CONFIG_SECURITY_SELINUX_DEVELOP 1
#undef CONFIG_SECURITY_SELINUX_MLS

/*
 * Cryptographic options
 */
#define CONFIG_CRYPTO 1
#define CONFIG_CRYPTO_HMAC 1
#define CONFIG_CRYPTO_NULL_MODULE 1
#define CONFIG_CRYPTO_MD4_MODULE 1
#define CONFIG_CRYPTO_MD5 1
#define CONFIG_CRYPTO_SHA1_MODULE 1
#define CONFIG_CRYPTO_SHA256_MODULE 1
#define CONFIG_CRYPTO_SHA512_MODULE 1
#define CONFIG_CRYPTO_DES_MODULE 1
#define CONFIG_CRYPTO_BLOWFISH_MODULE 1
#define CONFIG_CRYPTO_TWOFISH_MODULE 1
#define CONFIG_CRYPTO_SERPENT_MODULE 1
#define CONFIG_CRYPTO_AES_MODULE 1
#define CONFIG_CRYPTO_CAST5_MODULE 1
#define CONFIG_CRYPTO_CAST6_MODULE 1
#define CONFIG_CRYPTO_ARC4_MODULE 1
#define CONFIG_CRYPTO_DEFLATE_MODULE 1
#define CONFIG_CRYPTO_MICHAEL_MIC_MODULE 1
#define CONFIG_CRYPTO_CRC32C_MODULE 1
#undef CONFIG_CRYPTO_TEST

/*
 * Library routines
 */
#define CONFIG_CRC32 1
#define CONFIG_LIBCRC32C_MODULE 1
#define CONFIG_ZLIB_INFLATE 1
#define CONFIG_ZLIB_DEFLATE_MODULE 1
#define CONFIG_X86_SMP 1
#define CONFIG_X86_HT 1
#define CONFIG_X86_BIOS_REBOOT 1
#define CONFIG_X86_TRAMPOLINE 1
#define CONFIG_X86_STD_RESOURCES 1
#define CONFIG_PC 1
